import type { University } from './schema'

/**
 * Italy — read from official pages on 3 September 2026.
 *
 * HOW ITALIAN ADMISSION WORKS
 * Test-driven and rank-based. You sit a test, you get a score, the score puts
 * you in a ranking, and places are filled down the list. NO Italian university
 * in this file publishes an IB points requirement — at Bocconi and Sapienza we
 * confirmed there is none, and the rest simply never mention the IB.
 *
 * Do not assume TOLC. Three separate families of test are in play and they are
 * easy to confuse:
 *   TOL   — Politecnico di Milano's own test
 *   TIL   — Politecnico di Torino's own test
 *   CISIA — TOLC-I, English TOLC-I, TOLC-E, CEnT-S, Test HUM
 * Bologna has actively MOVED OFF TOLC-I onto CEnT-S for its English
 * engineering degree, and Sapienza uses CEnT-S for most of its English science
 * programmes. The old "engineering means TOLC-I" rule is now wrong in several
 * places.
 *
 * MONEY IS THE GOOD NEWS. Italian public universities means-test tuition. A
 * Turkish student at Sapienza with income declared abroad pays a flat
 * EUR 300–1,500 a year by country band. Politecnico di Torino scales the fee
 * by the home country's GDP. That is a tenth of the UK.
 */
export const IT_UNIVERSITIES: University[] = [
  {
    id: 'bocconi',
    name: 'Bocconi University',
    city: 'Milan',
    country: 'Italy',
    tier: 'high',
    admissionModel: 'test-ranked',
    headline: 'Rank is 55% test score and 45% school GPA. Nothing else counts — not the motivation letter, not the CV, not references.',
    ibNote: 'No IB points total is used. Bocconi states the evaluation rests solely on the test score and the GPA of the third-last and second-last school years. The IB appears only as a qualification awarded in English, satisfying the language condition.',
    satPolicy: 'accepted',
    satNote: 'SAT and ACT are treated as EQUIVALENT to Bocconi\'s own test. SAT total below 1040 or any section below 520 is not considered; scores before 2022 are not accepted. ACT composite below 19 is not considered.',
    tuitionCurrency: 'EUR',
    tuitionIntlMin: 17000,
    tuitionIntlMax: 17000,
    tuitionYear: '2026/27',
    applicationSystem: 'Bocconi online portal, early-selection rounds',
    deadlineNote: '2027/28 Early round 2–29 September 2026 with results in mid-November; Winter round 25 November 2026 – 26 January 2027.',
    cycle: '2027/28 selection rounds published; fees are 2026/27',
    checkedOn: '2026-09-03',
    sources: [
      'https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/application-and-admissions/admissions',
      'https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/application-and-admissions/online-bocconi-test',
      'https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/fees',
    ],
    gaps: ['Numeric IELTS and TOEFL minimums sit behind a link that did not render.'],
    areas: [
      { area: 'Medicine', offered: false },
      { area: 'Engineering', offered: false },
      {
        area: 'Computer Science', offered: true, course: 'Management and Computer Science; Mathematical and Computing Sciences for Artificial Intelligence',
        note: 'The AI programme sets a Mathematics floor on top of the overall minimum: SAT Math 600/800 or ACT Math 25/36. That sub-score is the real gate.',
        admissionsTest: 'Bocconi Online Test, SAT or ACT',
        testThreshold: 'Bocconi test 17/50 minimum; SAT 1040 total with 520 per section; AI programme additionally SAT Math 600',
        source: 'https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/application-and-admissions/sat-and-act',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics; Finance; Management; International Politics and Government',
        note: 'No named school subjects, but the mathematics expectation is built into the test: 24 of 50 questions are Mathematics — algebra, functions, geometry, trigonometry, logarithms, probability.',
        admissionsTest: 'Bocconi Online Test (50 questions, 75 minutes), SAT or ACT',
        testThreshold: 'Minimum 17/50 to be considered; final rank = 55% test + 45% GPA',
        source: 'https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/application-and-admissions/online-bocconi-test',
      },
      {
        area: 'Law', offered: true, course: 'Bachelor in Global Law',
        note: 'A different version of the test: only 5 Mathematics questions against 18 on logic and critical thinking and 10 on verbal reasoning. A student weak in mathematics is far better placed here than on the economics side.',
        admissionsTest: 'Bocconi Online Test – Law, or LSAT',
        source: 'https://www.unibocconi.it/en/programs/law-programs',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Management for the Arts and Cultures',
        note: 'A management degree about the arts sector, not a studio or design degree. No portfolio.',
      },
      { area: 'Psychology', offered: false },
    ],
  },

  {
    id: 'polimi',
    name: 'Politecnico di Milano',
    city: 'Milan',
    country: 'Italy',
    tier: 'high',
    admissionModel: 'test-ranked',
    headline: 'Pass mark is 30/100 on the TOL. Most bachelors are taught in Italian — only a handful are in English.',
    ibNote: 'No IB requirement found on any official page.',
    teachingLanguage: 'Italian for 22 of the bachelors; a small English-taught set',
    ieltsOverall: 5.0,
    ieltsNote: 'B2 equivalent before enrolment: IELTS 5.0, TOEFL iBT 59, Cambridge B2 First grade C. Exempt for citizens of English-speaking countries or secondary education completed in English.',
    satPolicy: 'accepted',
    satNote: 'SAT accepted as an alternative to the TOL with a minimum of 620 in each of the two sections.',
    tuitionCurrency: 'EUR',
    tuitionIntlMin: 167,
    tuitionIntlMax: 3893,
    tuitionYear: '2025/26 — ISEE income-scaled; a non-EU student with income abroad pays the maximum unless an ISEE is filed',
    applicationSystem: 'Politecnico online application; Universitaly pre-enrolment for the visa',
    deadlineNote: 'Early enrolment 4 May – 11 June 2026 for scores of 75/100 or above; standard preferences by 18 June 2026.',
    cycle: '2026/27',
    checkedOn: '2026-09-03',
    sources: [
      'https://www.polimi.it/fileadmin/user_upload/futuri_studenti/Engineering_BSc_call_for_admission_2026-27__English_.pdf',
      'https://www.polimi.it/en/prospective-students/how-much-does-it-cost/laurea-laurea-magistrale-and-single-cycle-programmes',
    ],
    gaps: ['The MEDTEC admissions page and the ARCHED test-content page are both blocked to automated reading.'],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'MEDTEC — Medicine and Biomedical Engineering, with Humanitas University',
        language: 'English',
        note: 'A combined medicine and biomedical engineering degree taught in English. Its admission test could not be verified — the page is blocked to automated reading, so check it directly.',
      },
      {
        area: 'Engineering', offered: true, course: 'Engineering Science (Milan); Industrial Engineering (Piacenza); Process Engineering (Cremona)',
        language: 'English',
        note: 'These three English-taught engineering bachelors were new for 2026/27 and described as pending ministerial approval. Everything else on the engineering side is Italian-taught.',
        admissionsTest: 'TOL — 65 questions in 100 minutes: English 30, Logic/Maths/Statistics 25, Verbal 5, Physics 5',
        testThreshold: '30/100 minimum; 75/100 opens early enrolment. Ties are broken on the Logic, Mathematics and Statistics section.',
        source: 'https://www.polimi.it/fileadmin/user_upload/futuri_studenti/Engineering_BSc_call_for_admission_2026-27__English_.pdf',
      },
      {
        area: 'Computer Science', offered: false, language: 'Italian',
        note: 'Engineering of Computing Systems is taught in Italian. There is no English-taught computer science bachelor at Politecnico di Milano.',
      },
      { area: 'Economics & Business', offered: false, language: 'Italian', note: 'Management and Production Engineering is Italian-taught.' },
      { area: 'Law', offered: false },
      {
        area: 'Architecture & Art', offered: true, course: 'Architectural Design; Interaction Design (Lecco)',
        language: 'Italian and English dual-language for Architectural Design; English for Interaction Design',
        note: 'A completely different test from engineering. Its published tiebreak order — logical reasoning, reading comprehension, design and rendering, physics and mathematics, general knowledge — is the only public clue to its content.',
        admissionsTest: 'ARCHED', testThreshold: 'Not published; scoring is +1 / 0 / −0.25 over 50 points',
        source: 'https://www.polimi.it/en/prospective-students/how-to-apply/admission-to-laurea-programmes/architecture/scores-and-rankings',
      },
      { area: 'Psychology', offered: false },
    ],
  },

  {
    id: 'sapienza',
    name: 'Sapienza University of Rome',
    city: 'Rome',
    country: 'Italy',
    tier: 'mid',
    admissionModel: 'test-ranked',
    headline: 'Eight English-taught bachelors, a pre-selection months before the official call, and tuition of EUR 300–1,500 a year.',
    ibNote: 'No IB points total is used. The IB is named only as an exemption from the English certificate requirement.',
    ieltsOverall: 5.5,
    ieltsNote: 'B2: IELTS 5.5, TOEFL iBT 80, Cambridge B2 First, Trinity ISE II. IB and GCSE holders are exempt.',
    tuitionCurrency: 'EUR',
    tuitionIntlMin: 300,
    tuitionIntlMax: 1500,
    tuitionYear: 'Flat country-band rate for students with income declared abroad: Band A EUR 300, Band B EUR 700, Band C EUR 1,500',
    applicationSystem: 'Move-In online pre-selection, then the official call',
    deadlineNote: 'Non-EU applicants needing a visa: 22 December 2025 – 15 May 2026. EU and equivalent: until 31 July 2026.',
    cycle: '2026/27',
    checkedOn: '2026-09-03',
    sources: [
      'https://www.uniroma1.it/sites/default/files/field_file_allegati/academic_requirements_movein_2026-2027_web_0.pdf',
      'https://www.uniroma1.it/en/pagina/applying-sapienza-international-student',
    ],
    gaps: ['The English-taught Medicine "Course F" does not name its 2026/27 admission test on any official page. Do not assume IMAT.'],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine and Surgery, Course F (English)',
        language: 'English',
        note: 'Sits outside the Move-In pre-selection. The faculty FAQ links to IMAT but does not name the test for 2026/27, and Sapienza uses TOLC-MED for its Italian-taught medicine. Verify before relying on it. Bioinformatics and Molecular Biology are the English-taught life-science alternatives, and Molecular Biology has the lowest GPA bar of the eight at 60/100.',
        admissionsTest: 'Not named for 2026/27',
        source: 'https://farmed.web.uniroma1.it/en/faq-english-course-f-medicine-and-surgery',
      },
      {
        area: 'Engineering', offered: true, course: 'Sustainable Building Engineering',
        language: 'English',
        admissionsTest: 'SAT or CEnT-S',
        testThreshold: 'CEnT-S converted score above zero; school GPA at least 80/100',
        source: 'https://www.uniroma1.it/sites/default/files/field_file_allegati/academic_requirements_movein_2026-2027_web_0.pdf',
      },
      {
        area: 'Computer Science', offered: true, course: 'Applied Computer Science and Artificial Intelligence',
        language: 'English',
        admissionsTest: 'SAT or CEnT-S',
        testThreshold: 'SAT above 960/1600 taken after 1 January 2024, or CEnT-S above zero; school GPA at least 75/100',
        note: 'A SAT of 960 is a genuinely low bar for an AI degree — this is one of the most accessible routes in the whole file.',
        source: 'https://www.uniroma1.it/sites/default/files/field_file_allegati/academic_requirements_movein_2026-2027_web_0.pdf',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Business Sciences; Economics and Finance',
        language: 'English',
        admissionsTest: 'SAT or CEnT-S',
        testThreshold: 'SAT above 960; Business Sciences also needs CEnT-S 18/55; school GPA at least 80/100 for both',
        source: 'https://www.uniroma1.it/sites/default/files/field_file_allegati/academic_requirements_movein_2026-2027_web_0.pdf',
      },
      { area: 'Law', offered: false, note: 'No English-taught law bachelor among the eight.' },
      {
        area: 'Architecture & Art', offered: false,
        note: 'No English-taught architecture or art bachelor. BA Classics and BA Global Humanities are the English humanities options, with GPA bars of 75 and 70.',
      },
      { area: 'Psychology', offered: false },
    ],
  },

  {
    id: 'unibo',
    name: 'University of Bologna',
    city: 'Bologna',
    country: 'Italy',
    tier: 'high',
    admissionModel: 'test-ranked',
    headline: 'Business and Economics ranks purely on SAT score with no minimum — 32 of its 190 places are reserved for non-EU applicants.',
    ibNote: 'No IB requirement found on any official page.',
    ieltsNote: 'Programme-specific. Genomics needs B2. Medicine assesses English inside the admission test with no separate certificate.',
    tuitionCurrency: 'EUR',
    tuitionIntlMin: 157,
    tuitionIntlMax: 157,
    tuitionYear: 'The fixed component only; the variable part is income-assessed and fully waived below EUR 27,000',
    applicationSystem: 'Per-programme calls; Universitaly pre-enrolment for non-EU applicants',
    deadlineNote: 'Set per programme. Business and Economics runs three rounds from 10 February 2026; Medicine registers 26 August – 9 September 2026 with the exam on 29 September.',
    cycle: '2026/27',
    checkedOn: '2026-09-03',
    sources: [
      'https://www.unibo.it/en/study/enrolment-fees-and-other-procedures/degree-programmes/enrolling-in-first-or-single-cycle-degree-programme-foreign-qualification',
      'https://www.unibo.it/en/study/enrolment-fees-and-other-procedures/degree-programmes/tuition-fees-and-exemptions',
    ],
    gaps: [
      'A complete list of English-taught bachelors could not be retrieved — the catalogue renders its filters but not its results.',
      'The maximum tuition figure lives in an Italian-language PDF that was not fetched.',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine and Surgery (single cycle)',
        language: 'English',
        note: '160 places, of which only 20 are for non-EU citizens residing abroad. The test is 60 multiple-choice questions: biology 23, chemistry 15, physics and mathematics 13, logical reasoning 5, general knowledge 4. Bologna does not brand it IMAT on its own page.',
        admissionsTest: '60-question admission test', testThreshold: 'Not published; ranking set in the call',
        source: 'https://corsi.unibo.it/singlecycle/MedicineAndSurgery/how-to-enrol',
      },
      {
        area: 'Engineering', offered: true, course: 'Building Construction Engineering (Ravenna)',
        language: 'English',
        note: 'Bologna has MOVED OFF TOLC-I for this degree — the page says so explicitly. Scoring below 8/15 in the Mathematics section does not block admission but triggers a remedial obligation. 150 of the first-round places are for non-EU applicants residing abroad.',
        admissionsTest: 'CEnT-S — 55 questions in 110 minutes across Mathematics, reasoning, Biology, Chemistry, Physics',
        source: 'https://corsi.unibo.it/1cycle/Building/how-to-enrol',
      },
      {
        area: 'Computer Science', offered: false, language: 'Italian',
        note: 'All five computing bachelors are Italian-taught and enter through TOLC-I.',
        source: 'https://disi.unibo.it/en/teaching/degree',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Business and Economics (CLaBE)',
        language: 'English',
        note: 'The SAT is the SOLE selection instrument and there is no minimum score — candidates are simply ranked in descending order. 190 places, 32 reserved for non-EU citizens outside Italy, across three rounds.',
        admissionsTest: 'SAT General Test, sat in person',
        testThreshold: 'No minimum; pure descending rank',
        source: 'https://corsi.unibo.it/1cycle/CLaBE/how-to-enrol',
      },
      { area: 'Law', offered: false, note: 'No English-taught first-cycle law programme confirmed.' },
      { area: 'Architecture & Art', offered: false, note: 'Not verified.' },
      { area: 'Psychology', offered: false, note: 'Not verified.' },
    ],
  },

  {
    id: 'polito',
    name: 'Politecnico di Torino',
    city: 'Turin',
    country: 'Italy',
    tier: 'mid',
    admissionModel: 'test-ranked',
    headline: '60/100 on the TIL guarantees a place. Tuition is scaled to your home country\'s GDP — Turkey lands in the lower bands.',
    ibNote: 'No IB requirement found on any official page.',
    ieltsNote: 'B2 or above required for English-taught programmes, but Politecnico publishes a certificate list without numeric thresholds.',
    satPolicy: 'accepted',
    satNote: 'SAT accepted with at least 650 in each section, but Politecnico warns it does NOT guarantee admission, and it is NOT valid for Architecture.',
    tuitionCurrency: 'EUR',
    tuitionIntlMin: 600,
    tuitionIntlMax: 3600,
    tuitionYear: '2025/26 — for non-EU students the fee is proportioned to the home country\'s GDP at purchasing power parity',
    applicationSystem: 'Politecnico Apply portal; Universitaly pre-enrolment mandatory by 30 June 2026',
    deadlineNote: 'The LAST TIL session for applicants needing a visa is 22 May 2026 — the July session is EU-only. Non-EU ranking closes 7 July 2026.',
    cycle: '2026/27',
    checkedOn: '2026-09-03',
    sources: [
      'https://www.polito.it/sites/default/files/2025-12/Call%20for%20applications%20for%20admissions%20Engineering%20_%20LP%202026-27.pdf',
      'https://www.polito.it/sites/default/files/2025-07/ENG_Regolamento%20contribuz_immatricolati_post%20CDA.pdf',
    ],
    gaps: ['One fee-annex figure (USA EUR 3,761) exceeds the stated maximum of EUR 3,600 and looks like a misread column — verify before quoting.'],
    areas: [
      { area: 'Medicine', offered: false },
      {
        area: 'Engineering', offered: true, course: 'Civil and Environmental; Electronic and Communications; Automotive; Mechanical Engineering',
        language: 'English',
        note: '447 places are reserved for non-EU applicants needing a visa. Mathematics dominates the test: 16 of 42 questions and 36 of the 90 minutes.',
        admissionsTest: 'TIL-I — Mathematics 16, Reading and Logic 10, Physics 10, Technical Knowledge 6',
        testThreshold: '30/100 to be admissible; 60/100 guarantees automatic admission to your first-preference course',
        source: 'https://www.polito.it/sites/default/files/2025-12/Call%20for%20applications%20for%20admissions%20Engineering%20_%20LP%202026-27.pdf',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Engineering',
        language: 'English',
        admissionsTest: 'TIL-I', testThreshold: '30/100 minimum, 60/100 guaranteed',
        source: 'https://www.polito.it/sites/default/files/2025-12/Call%20for%20applications%20for%20admissions%20Engineering%20_%20LP%202026-27.pdf',
      },
      { area: 'Economics & Business', offered: false, language: 'Italian', note: 'Engineering and Management is Italian-taught.' },
      { area: 'Law', offered: false },
      {
        area: 'Architecture & Art', offered: true, course: 'Architecture',
        language: 'English',
        note: 'A separate ministerial test, NOT the TIL — and the SAT is explicitly not valid here. The 2026/27 architecture call was still pending when checked.',
        admissionsTest: 'National architecture admission test set by the Ministry',
        source: 'https://www.polito.it/en/education/applying-studying-graduating/admissions-and-enrolment/bachelor-s-degree-programmes/calls-for-application-regulations-and-ranking-lists/calls-regulations-26-27',
      },
      { area: 'Psychology', offered: false },
    ],
  },
  /* ---------------------------------------------------------------- */
  {
    id: 'padova',
    name: 'University of Padua',
    city: 'Padua',
    country: 'Italy',
    tier: 'mid',
    admissionModel: 'test-ranked',
    headline: 'The only Italian university here with a real 2027 calendar published — and it reserves 100 non-EU places on Information Engineering alone.',
    ibNote: 'No IB points total. The requirement is a school record of at least twelve years; eligibility is set country by country.',
    ieltsNote: 'B1 or B2 depending on the programme. The numeric IELTS and TOEFL table sits in a PDF and could not be read.',
    tuitionCurrency: 'EUR',
    tuitionIntlMin: 2790,
    tuitionIntlMax: 2990,
    tuitionYear: '2026/27 — non-EU students pay a FIXED fee, not ISEE-assessed: EUR 2,790 for humanities, EUR 2,990 for sciences, plus a EUR 208 first instalment. Students from low-development countries pay about a third.',
    applicationSystem: 'apply.unipd.it, except Medicine which runs through the national IMAT route on Universitaly',
    deadlineNote: '2027/28 intake opens 15 September 2026. Non-EU residing abroad: 7 January – 7 March 2027. EU: 9 March – 9 April 2027.',
    cycle: '2027/28 dates published; fees 2026/27',
    checkedOn: '2026-09-03',
    sources: [
      'https://www.unipd.it/en/corsi-laurea-lingua-inglese',
      'https://www.unipd.it/en/contribuzione-studentesca',
      'https://apply.unipd.it/news/new/68-cent-s-new-unified-cisia-entry-test-english-taught-bachelors-programmes',
    ],
    gaps: ['Padua moved its English bachelors onto CEnT-S, the new CISIA test that replaced English TOLC from November 2025. The old "engineering means TOLC-I" assumption is wrong here.'],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine and Surgery (English); also MedTech',
        language: 'English',
        note: '25 places reserved for non-EU applicants residing abroad.',
        admissionsTest: 'IMAT', testThreshold: 'National floor 20/90 to be ranked',
        testLocations: 'Italy or a certified centre abroad; test 29 September 2026, registration 26 August – 9 September on Universitaly',
        tuition: 'EUR 2,950 per year',
        source: 'https://apply.unipd.it/courses/course/36-medicine-and-surgery?search=58698',
      },
      {
        area: 'Engineering', offered: true, course: 'Information Engineering',
        language: 'English',
        note: '100 places reserved for non-EU applicants residing abroad — the largest reserved allocation found anywhere in this file.',
        admissionsTest: 'CEnT-S (CISIA), EUR 55, four sittings a year, in person or remote',
        source: 'https://apply.unipd.it/courses/course/182-information-engineering',
      },
      { area: 'Computer Science', offered: true, course: 'Information Engineering', language: 'English', note: 'Padua has no separate English computer science bachelor; Information Engineering is the route.', admissionsTest: 'CEnT-S' },
      {
        area: 'Economics & Business', offered: true, course: 'Economics, Governance and Decision-Making',
        language: 'English', note: '30 non-EU places reserved. Mathematics for Social Sciences is first-year content; no prior subject is demanded.',
        admissionsTest: 'CEnT-S',
        source: 'https://apply.unipd.it/courses/course/258-economics-governance-and-decision-making',
      },
      { area: 'Law', offered: false, language: 'Italian' },
      { area: 'Architecture & Art', offered: false },
      {
        area: 'Psychology', offered: true, course: 'Psychological Science; Techniques and Methods in Psychological Science',
        language: 'English', note: '45 non-EU places reserved. Uses Padua’s OWN psychology entry test in English, not CEnT-S.',
        admissionsTest: 'Padua psychology entry test (English)',
        source: 'https://apply.unipd.it/courses/course/27-psychological-science',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'unimib',
    name: 'University of Milano-Bicocca',
    city: 'Milan; Medicine in English is taught in Bergamo',
    country: 'Italy',
    tier: 'mid',
    admissionModel: 'test-ranked',
    headline: 'Tuition is set by your country’s income group — from EUR 200 to EUR 3,600 a year, with no ISEE paperwork.',
    ibNote: 'No IB points total. A final secondary diploma from twelve or more years of schooling, translated, plus an academic-suitability certificate where the home country requires one.',
    ieltsNote: 'B2 required for English-taught courses; the numeric minimums are not published. Certificate deadline 31 July 2026.',
    tuitionCurrency: 'EUR',
    tuitionIntlMin: 200,
    tuitionIntlMax: 3600,
    tuitionYear: '2025/26 figures — three country groups by GDP per head crossed with two course areas, plus a EUR 156 first instalment. The 2026/27 amounts were not retrievable, though the mechanism is unchanged.',
    applicationSystem: 'apply.unimib.it (DreamApply); EUR 30 application fee and a EUR 150 deposit, both non-refundable',
    deadlineNote: 'Limited-places call 1: 10 February – 31 March 2026. Later calls are EU-only. Medicine in English closes 26 September 2026.',
    cycle: '2026/27',
    checkedOn: '2026-09-03',
    sources: [
      'https://apply.unimib.it/en_GB/news/new/39-apply-202627-admission-calls-and-deadlines',
      'https://en.unimib.it/node/3940',
      'https://www.unimib.it/sites/default/files/2025-07/Guida%20CONTRIBUZIONE%2025_26_0.pdf',
    ],
    gaps: [
      'Bicocca’s "international courses" page mixes bachelor and master programmes — International Economics and Applied Experimental Psychological Sciences are MASTER’S, not bachelors. Do not read that page as a bachelor list.',
      'Bicocca does not publish the EU / non-EU place split for Medicine.',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine and Surgery (English), taught in Bergamo',
        language: 'English',
        note: 'Problem-based learning across seven physiological systems. The test is sat at Bicocca in Milan even though the course runs in Bergamo.',
        admissionsTest: 'IMAT', testLocations: 'Piazza dell’Ateneo Nuovo, Milan, 29 September 2026',
        source: 'https://en.unimib.it/node/3940',
      },
      { area: 'Engineering', offered: false, note: 'Bicocca has no engineering faculty.' },
      {
        area: 'Computer Science', offered: true, course: 'Artificial Intelligence (joint with Milan Statale and Pavia)',
        language: 'English',
        note: '180 places in total, 50 reserved for non-EU applicants abroad. Administered by Pavia. Below the maths threshold you are admitted but carry a remedial obligation.',
        admissionsTest: 'English TOLC-I for EU applicants; SAT for non-EU applicants residing abroad',
        source: 'https://www.unimi.it/en/education/bachelor/artificial-intelligence',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics and Science for Environmental Sustainability',
        language: 'English',
        admissionsTest: 'Numero programmato test — Mathematics, Logic, Reading Comprehension',
        testThreshold: '13 points to enter the ranking; remedial obligation below 4 in Mathematics, 3 in Logic or 3 in Reading',
        source: 'https://www.unimib.it/node/33000',
      },
      { area: 'Law', offered: false, language: 'Italian' },
      { area: 'Architecture & Art', offered: false },
      { area: 'Psychology', offered: false, language: 'Italian', note: 'Italian-taught at bachelor level; the English psychology programme is a master’s.' },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'pavia',
    name: 'University of Pavia',
    city: 'Pavia',
    country: 'Italy',
    tier: 'mid',
    admissionModel: 'test-ranked',
    headline: 'The Harvey Course is one of the best-known English medical degrees in Italy — and IMAT scores around 60-65/90 are what actually get in.',
    ibNote: 'No IB points total. The Harvey page names expectations for two systems only — three scientific A-levels for UK applicants, three scientific APs for US applicants — and says nothing about the IB.',
    ieltsNote: 'B2 for the AI bachelor and for Social Sciences for Global Challenges. Numeric minimums not published.',
    tuitionCurrency: 'EUR',
    tuitionIntlMin: 390,
    tuitionIntlMax: 4550,
    tuitionYear: '2026/27 — non-EU students may take an automatic Flat Rate set by citizenship and field, with no financial paperwork, or submit documentation for an income-adjusted fee. The bracket is then fixed for the whole degree plus one year.',
    applicationSystem: 'Universitaly and the national IMAT for Medicine; apply.unipv.eu for the EUR 35 foreign-diploma evaluation',
    deadlineNote: 'Non-EU residing abroad must pre-enrol on Universitaly by 31 August. IMAT registration 26 August – 9 September 2026; test 29 September. After the ranking, enrolment closes within four days.',
    cycle: '2026/27',
    checkedOn: '2026-09-03',
    sources: [
      'https://medicineandsurgeryharvey.cdl.unipv.it/en/enroll/admission-test',
      'https://en.unipv.it/en/education/bachelors-and-masters-degree-programs/fees-and-funding/fees/prospective-students/non-eu-students',
    ],
    gaps: [
      'Pavia does not publish the non-EU place count for Harvey Medicine — it is inside the annual call PDF.',
      'During 2025/26 Pavia carried a live warning that all non-EU-residing-abroad places had already been assigned. Apply early.',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine and Surgery — Harvey Course, 6 years',
        language: 'English',
        admissionsTest: 'IMAT — 60 questions, 100 minutes, 90 points, +1.5 / −0.4 / 0',
        testThreshold: '20/90 minimum to be ranked. Pavia’s own page notes that competitive scores have historically run around 60-65/90 — commentary, not a rule.',
        testLocations: 'Italy or one of the other available countries; 29 September 2026',
        source: 'https://medicineandsurgeryharvey.cdl.unipv.it/en/enroll/admission-test',
      },
      {
        area: 'Engineering', offered: true, course: 'Building Engineering and Architecture, 5 years',
        language: 'English and Italian — bilingual, NOT fully English',
        note: 'Listed as a dual-language single-cycle degree. Check the language split before relying on it.',
      },
      {
        area: 'Computer Science', offered: true, course: 'Artificial Intelligence (joint, administered by Pavia)',
        language: 'English',
        note: '180 places, 50 for non-EU applicants abroad.',
        admissionsTest: 'English TOLC-I (EU) or SAT (non-EU abroad)',
        source: 'https://www.unimi.it/en/education/bachelor/artificial-intelligence',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Social Sciences for Global Challenges',
        language: 'English',
        note: 'NOT restricted-access — the entrance test is non-selective and only certifies general knowledge. The nearest thing to open admission in this file.',
        admissionsTest: 'Non-selective general-knowledge test',
        source: 'https://en.unipv.it/en/education/bachelors-and-masters-degree-programs/first-cycle-degree-course/social-sciences-global-challenges',
      },
      { area: 'Law', offered: false, language: 'Italian' },
      { area: 'Architecture & Art', offered: true, course: 'Building Engineering and Architecture', language: 'English and Italian' },
      { area: 'Psychology', offered: false, language: 'Italian' },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'unito',
    name: 'University of Turin',
    city: 'Turin; Medicine in English at Orbassano',
    country: 'Italy',
    tier: 'mid',
    admissionModel: 'test-ranked',
    headline: 'Uses the SAT for its English business degrees — and ranks on the LAST sitting, not your best. Sit it once, carefully.',
    ibNote: 'No IB points total. A high school diploma giving university access at home after at least twelve years, assessed for comparability under the Lisbon Convention.',
    ieltsNote: 'B2. Global Law accepts English TOLC-E with at least 4 in Reading Comprehension, or TOLC-SU with at least 12 in the English section, by 15 July 2026.',
    satPolicy: 'required',
    satNote: 'Required for Business & Management and for Economics and Finance with Data Science. College Board code 9136. Turin uses the score of the LAST test taken, not the highest — and rejects results without a fiscal code on them.',
    tuitionCurrency: 'EUR',
    tuitionIntlMin: 500,
    tuitionIntlMax: 1650,
    tuitionYear: '2026/27 — banded by the GDP per head of your country of residence, from EUR 500 to EUR 1,500 in the first two years, plus a EUR 156 first instalment. The band must be claimed by 20 November 2026 or the maximum applies.',
    applicationSystem: 'Apply@UniTo, EUR 60 covering up to two programmes',
    deadlineNote: 'Undergraduate applications with a foreign qualification: 19 February – 15 April 2026. SAT and TOLC procedures close 6 June 2026, second round 12 September. Universitaly pre-enrolment by 15 July 2026.',
    cycle: '2026/27',
    checkedOn: '2026-09-03',
    sources: [
      'https://en.unito.it/studying-unito/tuition-fees/tuition-fees-international-students',
      'https://en.unito.it/studying-unito/enrolment-procedure/undergraduate-degrees-restricted-number-places/undergraduate',
      'https://apply.unito.it/en_GB/courses/course/462-medicine-and-surgery',
    ],
    gaps: ['Turin’s own pages conflict on tuition: the international fees page caps the banded fee at EUR 1,500, while course pages quote EUR 2,800 a year. The likely reading is that EUR 2,800 is the standard maximum and the band is the reduction you claim — but no page says so. Do not quote a single Turin figure without this caveat.'],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine and Surgery — MedInTO',
        language: 'English',
        note: '30 places reserved for non-EU applicants residing abroad. Candidates scoring 25% below the top mark in Physics and Biology are admitted but must complete a study supplement.',
        admissionsTest: 'IMAT', testLocations: 'All Italian universities offering the programme, plus worldwide test sites',
        source: 'https://www.medinto.unito.it/do/home.pl/View?doc=Admission_requirements.html',
      },
      { area: 'Engineering', offered: false, note: 'Engineering in Turin sits at Politecnico di Torino, a separate institution.' },
      { area: 'Computer Science', offered: false, note: 'No English computer science bachelor at UniTo.' },
      {
        area: 'Economics & Business', offered: true, course: 'Business & Management; Economics and Finance with Data Science',
        language: 'English',
        admissionsTest: 'SAT (College Board code 9136)',
        testThreshold: 'No minimum published; ranked on the LAST sitting',
        source: 'https://en.unito.it/studying-unito/enrolment-procedure/undergraduate-degrees-restricted-number-places/undergraduate',
      },
      {
        area: 'Law', offered: true, course: 'Global Law and Transnational Legal Studies',
        language: 'English',
        note: '250 places reserved for non-EU applicants residing abroad — by far the most open English law route found. No selective subject test.',
        source: 'https://apply.unito.it/en_GB/courses/course/543-global-law-and-transnational-legal-studies',
      },
      { area: 'Architecture & Art', offered: false, language: 'Italian' },
      { area: 'Psychology', offered: false, language: 'Italian' },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'unimi',
    name: 'University of Milan (La Statale)',
    city: 'Milan',
    country: 'Italy',
    tier: 'mid',
    admissionModel: 'test-ranked',
    headline: 'IPLE reserves 25 of its 150 places for non-EU applicants and runs a dedicated spring selection for them.',
    ibNote: 'No IB points total. An upper secondary diploma after at least twelve years, with an official Italian translation, legalisation, and a CIMEA comparability statement or an embassy declaration of value.',
    ieltsNote: 'B2. IPLE accepts a certificate issued within the last three years, an English-medium diploma, or the university placement test — failing the test means taking a language course, not rejection.',
    tuitionCurrency: 'EUR',
    tuitionIntlMin: 200,
    tuitionIntlMax: 4101,
    tuitionYear: '2026/27 — students with income generated outside Italy pay a flat fee by country group and course area, not ISEE, plus a EUR 146 first instalment.',
    applicationSystem: 'Per-programme; Universitaly pre-application for non-EU applicants',
    deadlineNote: 'Universitaly pre-application for bachelors by 31 July 2026, naming ONE university and ONE programme only. IPLE applications 12 March – 6 July 2026. Documents by 30 November 2026.',
    cycle: '2026/27',
    checkedOn: '2026-09-03',
    sources: [
      'https://www.unimi.it/en/international/coming-abroad/enrol-programme/programmes-english',
      'https://www.unimi.it/en/study/bachelor-and-master-study/fees-and-how-pay-them/fees-2026/2027',
      'https://iple.cdl.unimi.it/en/enrolment',
    ],
    gaps: ['Which country group Turkey falls into was not retrievable — the table was not published on the pages fetched.'],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine and Surgery — International Medical School',
        language: 'English',
        note: 'A remedial obligation is assigned below 45/90 overall or below 13.5/27 on the biology questions, to be cleared before certain exams.',
        admissionsTest: 'IMAT', testLocations: 'Certified centres; 29 September 2026',
        source: 'https://ims.cdl.unimi.it/en/enrolment',
      },
      { area: 'Engineering', offered: false, note: 'Engineering in Milan sits at Politecnico di Milano, a separate institution.' },
      {
        area: 'Computer Science', offered: true, course: 'Artificial Intelligence (joint with Bicocca and Pavia)',
        language: 'English', note: '180 places, 50 for non-EU applicants abroad.',
        admissionsTest: 'English TOLC-I (EU) or SAT (non-EU abroad)',
        source: 'https://www.unimi.it/en/education/bachelor/artificial-intelligence',
      },
      {
        area: 'Economics & Business', offered: true, course: 'International Politics, Law and Economics (IPLE); Economics: behavior, data and policy',
        language: 'English',
        note: 'IPLE has 125 places plus 25 reserved for non-EU citizens, with a dedicated spring selection for applicants abroad.',
        admissionsTest: 'IPLE admission test — language comprehension, logic, mathematics',
        testThreshold: 'At least 50% in each of the three areas to avoid a remedial obligation',
        source: 'https://iple.cdl.unimi.it/en/enrolment',
      },
      { area: 'Law', offered: true, course: 'International Politics, Law and Economics (IPLE)', language: 'English', note: 'Law is one strand of IPLE; there is no standalone English law bachelor.' },
      { area: 'Architecture & Art', offered: false },
      { area: 'Psychology', offered: false, language: 'Italian' },
    ],
  },
]

/*
 * Italy now holds ten universities. Still missing: a genuinely
 * accessible tier — Ferrara, Parma, Siena, Bari or Catania, several of which
 * also run IMAT medicine in English with less competition than Pavia or Milan.
 */
