import type { University } from './schema'

/**
 * United Kingdom — 20 universities, read from official .ac.uk pages on
 * 2 September 2026.
 *
 * HOW TO READ THIS FILE
 * - Every figure came from the page named in `source`. Nothing is estimated.
 * - An absent field means the university does not publish it, or the page
 *   could not be read. `gaps` says which.
 * - `cycle` differs between universities because they publish on different
 *   schedules. Some are already on 2027 entry, others still on 2026.
 * - Requirements change every year. `checkedOn` is the expiry clock: anything
 *   older than about ten months should be re-read before a student relies on it.
 *
 * NOT IN THIS FILE
 * Acceptance rates. They are an institutional statistic, not a personal
 * probability, and an unsourced one misleads a student building a shortlist.
 */
export const UK_UNIVERSITIES: University[] = [
  /* ---------------------------------------------------------------- */
  {
    id: 'oxford',
    name: 'University of Oxford',
    city: 'Oxford',
    country: 'United Kingdom',
    tier: 'high',
    ibTypicalLow: 38,
    ibTypicalHigh: 40,
    ibNote: '38, 39 or 40 points including core points depending on the course, with 6s and 7s at Higher Level.',
    aLevelTypical: 'AAA – A*A*A',
    ieltsOverall: 7.5,
    ieltsComponent: 7.0,
    ieltsNote: 'TOEFL iBT 110 with Listening 22, Reading 24, Speaking 25, Writing 24. All undergraduate courses now require the higher level.',
    satPolicy: 'unknown',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 39620,
    tuitionIntlMax: 66580,
    tuitionYear: '2027/28',
    applicationSystem: 'UCAS',
    deadlineNote: '15 October 2026, 6pm UK time — for every course, including international applicants.',
    cycle: '2027 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.ox.ac.uk/admissions/undergraduate/applying-to-oxford/for-international-students',
      'https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/course-fees',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine (A100), 6 years',
        ibPoints: 39, ibHl: '7,6,6',
        hlRequired: ['Chemistry', 'one of Biology, Physics or Mathematics'],
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/medicine',
      },
      {
        area: 'Engineering', offered: true, course: 'Engineering Science',
        ibPoints: 40, ibHl: '7,7,6',
        hlRequired: ['Mathematics', 'Physics'],
        note: 'Both Mathematics and Physics must be at grade 7.',
        admissionsTest: 'ESAT (Mathematics 1, Mathematics 2 and Physics modules)', interview: true,
        source: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/engineering-science',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science',
        ibPoints: 39, ibHl: '7,6,6',
        hlRequired: ['Mathematics'],
        note: 'The 7 must be in Mathematics.',
        admissionsTest: 'TMUA (Papers 1 and 2)', interview: true,
        source: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/computer-science',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics and Management',
        ibPoints: 39, ibHl: '7,6,6',
        hlRequired: ['Mathematics'],
        admissionsTest: 'TARA', interview: true,
        source: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/economics-and-management',
      },
      {
        area: 'Law', offered: true, course: 'Law (Jurisprudence)',
        ibPoints: 38, ibHl: '6,6,6',
        hlRecommended: ['an essay-writing subject'],
        note: 'Course II additionally requires B2 proficiency in French, German, Italian or Spanish.',
        admissionsTest: 'LNAT', interview: true,
        source: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/law-jurisprudence',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Fine Art (BFA)',
        ibPoints: 38, ibHl: '6,6,6',
        note: 'Oxford has no undergraduate Architecture degree. A post-18 Art Foundation course is strongly advised and lowers the A-level offer to AAB.',
        portfolio: true, interview: true,
        source: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/fine-art',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology (Experimental)',
        ibPoints: 39, ibHl: '7,6,6',
        hlRecommended: ['a science subject or Mathematics'],
        admissionsTest: 'TARA (including the Writing Task)', interview: true,
        source: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/psychology-experimental',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    city: 'Cambridge',
    country: 'United Kingdom',
    tier: 'high',
    ibTypicalLow: 41,
    ibTypicalHigh: 42,
    ibNote: '41–42 points with 776 at Higher Level is the MINIMUM, not a typical offer. Some Colleges ask for 777 or a higher total, and requirements differ between Colleges. Course differentiation happens at A-level and in subject requirements, not in the IB total.',
    aLevelTypical: 'A*AA – A*A*A',
    ieltsOverall: 7.5,
    ieltsComponent: 7.0,
    ieltsNote: 'TOEFL is not listed among accepted tests. Cambridge English C1 Advanced 193 or C2 Proficiency 200 are accepted instead.',
    satPolicy: 'accepted',
    satNote: 'One US route among several: SAT 1500 combined with Mathematics 750+ for science and economics courses (1460 with EBRW 730+ for others), or ACT 33+ for science (32+ for others). Five APs at 5 is the alternative.',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 29052,
    tuitionIntlMax: 70554,
    tuitionYear: '2026/27',
    applicationSystem: 'UCAS, plus the separate My Cambridge Application form',
    deadlineNote: 'UCAS 15 October 2026, 6pm. My Cambridge Application and transcripts 22 October 2026, 6pm.',
    cycle: '2027 entry (requirements); 2026/27 fees',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.undergraduate.study.cam.ac.uk/apply/before/entry-requirements',
      'https://www.undergraduate.study.cam.ac.uk/international-students/international-fees-and-costs',
    ],
    gaps: ['A College fee of £11,500–£14,950 is charged on top of the tuition figures above.'],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine (MB, BChir) A100',
        ibPoints: 41, ibHl: '7,7,6',
        hlRequired: ['Chemistry'],
        note: 'Colleges typically want 7 in Chemistry, plus one or two further subjects from Mathematics, Biology, Physics — how many depends on the College. Must be 18 by 1 November of Year 1.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.undergraduate.study.cam.ac.uk/courses/medicine',
      },
      {
        area: 'Engineering', offered: true, course: 'Engineering (BA/MEng)',
        ibPoints: 41, ibHl: '7,7,6',
        hlRequired: ['Mathematics', 'Physics'],
        note: 'Both typically at grade 7.',
        admissionsTest: 'ESAT (Mathematics 1, Mathematics 2, Physics)',
        source: 'https://www.undergraduate.study.cam.ac.uk/courses/engineering',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science (BA/MEng)',
        ibPoints: 41, ibHl: '7,7,6',
        hlRequired: ['Mathematics: Analysis and Approaches'],
        note: 'Applications and Interpretation is not accepted. Peterhouse and Trinity additionally require the CSAT. Churchill, Lucy Cavendish and Selwyn set higher offers.',
        admissionsTest: 'TMUA',
        source: 'https://www.undergraduate.study.cam.ac.uk/courses/computer-science',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BA',
        ibPoints: 41, ibHl: '7,7,6',
        hlRequired: ['Mathematics: Analysis and Approaches'],
        admissionsTest: 'TMUA',
        source: 'https://www.undergraduate.study.cam.ac.uk/courses/economics',
      },
      {
        area: 'Law', offered: true, course: 'Law BA',
        ibPoints: 41, ibHl: '7,7,6',
        note: 'No specific subjects required. Some Colleges request submitted written work.',
        admissionsTest: 'LNAT',
        source: 'https://www.undergraduate.study.cam.ac.uk/courses/law',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Architecture (BA/MArch)',
        ibPoints: 41, ibHl: '7,7,6',
        hlRecommended: ['Mathematics', 'Art and Design', 'Physics'],
        note: 'Some Colleges ask for specific subjects, others do not. Artwork is submitted in advance (PDF, max 6 A4 pages) and a portfolio is brought to interview.',
        admissionsTest: 'College admission assessment', interview: true, portfolio: true,
        source: 'https://www.undergraduate.study.cam.ac.uk/courses/architecture',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychological and Behavioural Sciences BA',
        ibPoints: 41, ibHl: '7,7,6',
        hlRequired: ['one of Mathematics, Biology, Chemistry, Computer Science or Physics'],
        admissionsTest: 'Admissions assessment at some Colleges',
        source: 'https://www.undergraduate.study.cam.ac.uk/courses/psychological-and-behavioural-sciences',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'imperial',
    name: 'Imperial College London',
    city: 'London',
    country: 'United Kingdom',
    tier: 'high',
    ibTypicalLow: 38,
    ibTypicalHigh: 42,
    ibNote: 'Imperial publishes both a minimum and a typical offer for each course. There is no university-wide figure. The numbers below are the typical offers.',
    aLevelTypical: 'A*AA – A*A*A*',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Standard level 6.5/6.0; higher level 7.0/6.5, used by Medicine and Economics. Must be met in one sitting.',
    satPolicy: 'unknown',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 42700,
    tuitionIntlMax: 58600,
    tuitionYear: '2026/27',
    applicationSystem: 'UCAS',
    deadlineNote: 'Medicine 15 October 2026. All other courses 13 January 2027.',
    cycle: '2027 entry (fees are 2026/27; 2027 fees not yet set)',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.imperial.ac.uk/study/apply/undergraduate/entry-requirements/',
      'https://www.imperial.ac.uk/study/apply/english-language/',
    ],
    gaps: ['Imperial publishes tuition per course; the min and max above are the three courses actually checked, not a full range.'],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine MBBS/BSc',
        ibPoints: 39, ibPointsMin: 38, ibHl: '7,6 in Biology and Chemistry',
        hlRequired: ['Biology', 'Chemistry'],
        note: 'Minimum 38 with 6 in both; typical 39 with 6 and 7.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.imperial.ac.uk/study/courses/undergraduate/medicine/',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering MEng',
        ibPoints: 40, ibHl: '7,7 in Mathematics and Physics',
        hlRequired: ['Mathematics', 'Physics'],
        note: 'Minimum 40 with 6 in both; typical 40 with 7 in both.',
        admissionsTest: 'ESAT', interview: true,
        source: 'https://www.imperial.ac.uk/study/courses/undergraduate/mechanical-engineering/',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computing MEng',
        ibPoints: 42, ibPointsMin: 41, ibHl: '7 in Mathematics and 7 in another relevant subject',
        hlRequired: ['Mathematics'],
        note: 'The highest IB requirement of any course in this file. Interviews are not standard but may be offered.',
        admissionsTest: 'TMUA',
        source: 'https://www.imperial.ac.uk/study/courses/undergraduate/computing-meng/',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics, Finance and Data Science BSc',
        ibPoints: 39, ibHl: '7,6,6',
        hlRequired: ['Mathematics'],
        note: 'Mathematics must be at grade 7. Further Mathematics and Economics are suggested but not required.',
        admissionsTest: 'TMUA', interview: true,
        source: 'https://www.imperial.ac.uk/study/courses/undergraduate/economics-finance-data-science/',
      },
      { area: 'Law', offered: false },
      { area: 'Architecture & Art', offered: false },
      { area: 'Psychology', offered: false },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'lse',
    name: 'London School of Economics and Political Science',
    city: 'London',
    country: 'United Kingdom',
    tier: 'high',
    ibTypicalLow: 37,
    ibTypicalHigh: 39,
    ibNote: 'Offers are a total plus a three-digit HL string. Contextual offers run one to two points lower with 666 at HL.',
    aLevelTypical: 'A*AA – AAB',
    ieltsOverall: 7.0,
    ieltsComponent: 7.0,
    ieltsNote: 'Must be achieved in one sitting and be no more than two years old at the start date.',
    satPolicy: 'unknown',
    satNote: 'LSE references Advanced Placement, requiring at least five AP subjects. No SAT or ACT threshold is published.',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 28900,
    tuitionIntlMax: 39900,
    tuitionYear: '2026/27',
    applicationSystem: 'UCAS — direct applications are not considered',
    deadlineNote: 'UCAS equal-consideration deadline in mid-January. LNAT for the LLB must be sat by 31 December 2026.',
    cycle: '2027/28 entry (fees are 2026/27)',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.lse.ac.uk/study-at-lse/Undergraduate/Prospective-Students/How-to-Apply/entry-requirements',
      'https://www.lse.ac.uk/study-at-lse/Undergraduate/fees-and-funding',
    ],
    areas: [
      { area: 'Medicine', offered: false },
      { area: 'Engineering', offered: false },
      {
        area: 'Computer Science', offered: true, course: 'Data Science BSc',
        ibPoints: 39, ibPointsMin: 38, ibHl: '7,6,6',
        hlRequired: ['Mathematics: Analysis and Approaches'],
        note: 'LSE has no dedicated Computer Science degree. Mathematics must be at grade 7.',
        source: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-data-science',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        ibPoints: 39, ibHl: '7,6,6',
        hlRequired: ['Mathematics'],
        note: 'Mathematics at grade 7. BSc Management is a lower offer: 38 with 766 including HL Mathematics.',
        admissionsTest: 'TMUA',
        source: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economics',
      },
      {
        area: 'Law', offered: true, course: 'LLB Bachelor of Laws',
        ibPoints: 39, ibPointsMin: 37, ibHl: '7,6,6',
        note: 'No subject requirements. Contextual offer 37 with 666.',
        admissionsTest: 'LNAT',
        source: 'https://www.lse.ac.uk/study-at-lse/undergraduate/llb-bachelor-of-laws',
      },
      { area: 'Architecture & Art', offered: false },
      {
        area: 'Psychology', offered: true, course: 'Psychological and Behavioural Science BSc',
        ibPoints: 39, ibHl: '7,6,6',
        hlRequired: ['one of Biology, Chemistry, Physics, Mathematics or Psychology'],
        source: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-psychological-and-behavioural-science',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'ucl',
    name: 'University College London',
    city: 'London',
    country: 'United Kingdom',
    tier: 'high',
    ibTypicalLow: 34,
    ibTypicalHigh: 40,
    ibNote: 'UCL quotes HL points on course pages, not the overall total. Its own mapping: 20 HL points = 40 overall, 19 = 39, 18 = 38, 17 = 36, 16 = 34. A minimum of 5 is required in EACH Higher Level subject.',
    aLevelTypical: 'A*A*A – ABB',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Five levels, set per course: Level 1 is 6.5/6.0, Level 4 (Medicine, Law) is 7.5/7.0. TOEFL MyBestScore is not accepted.',
    satPolicy: 'unknown',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 35400,
    tuitionIntlMax: 59600,
    tuitionYear: '2027/28 (some course pages still show 2026/27)',
    applicationSystem: 'UCAS — direct applications are not accepted',
    deadlineNote: '13 January 2027, 6pm, for most courses. Medicine 15 October 2026.',
    cycle: 'September 2027 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.ucl.ac.uk/prospective-students/undergraduate/entry-requirements',
      'https://www.ucl.ac.uk/study/prospective-students/undergraduate/how-apply/english-language-requirements',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine MBBS BSc',
        ibPoints: 39, ibHl: '19 HL points, no HL below 5',
        hlRequired: ['Biology', 'Chemistry'],
        note: 'Grades 6 and 7 in Biology and Chemistry, in either order. English requirement is Level 4 (IELTS 7.5).',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/medicine-mbbs-bsc',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering MEng',
        ibPoints: 39, ibHl: '19 HL points, no HL below 5',
        hlRequired: ['Mathematics', 'Physics'],
        note: 'Grades 7 and 6. Either Mathematics stream is accepted.',
        admissionsTest: 'TARA',
        source: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/mechanical-engineering-meng',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 40, ibPointsMin: 38, ibHl: '20 HL points',
        hlRequired: ['Mathematics'],
        note: 'Mathematics at grade 7; Analysis and Approaches preferred. Contextual offer 18 HL points.',
        admissionsTest: 'TARA',
        source: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/computer-science-bsc',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc (Econ)',
        ibPoints: 39, ibHl: '19 HL points including 7 in Mathematics',
        hlRequired: ['Mathematics'],
        note: 'Either Mathematics stream. English requirement Level 2 (IELTS 7.0).',
        admissionsTest: 'TMUA',
        source: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/economics-bsc-econ',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 39, ibPointsMin: 36, ibHl: '19 HL points, no HL below 5',
        note: 'No HL subject required, but two A-level-equivalent subjects should come from UCL’s preferred list. English requirement Level 4 (IELTS 7.5).',
        admissionsTest: 'LNAT',
        source: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/law-llb',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Architecture BSc',
        ibPoints: 36, ibHl: '17 HL points, no HL below 5',
        note: 'No subject requirement. The most accessible entry point at UCL among the courses checked.',
        portfolio: true, interview: true,
        source: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/architecture-bsc',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 39, ibHl: '19 HL points, no HL below 5',
        hlRequired: ['two of Biology, Chemistry, Mathematics, Physics or Psychology'],
        note: 'At grades 7 and 6. English requirement Level 3 (IELTS 7.0 in every component).',
        source: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/psychology-bsc',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'kcl',
    name: "King's College London",
    city: 'London',
    country: 'United Kingdom',
    tier: 'high',
    ibTypicalLow: 36,
    ibTypicalHigh: 39,
    ibNote: 'Offers are stated as either a total OR an aggregate of three HL grades, e.g. "38 points overall or an aggregate of 19 from three Higher Levels". Across the whole institution requirements run from 29 to 40 points. Contextual offers are about 3 points lower.',
    aLevelTypical: 'AAA – A*A*A (institution-wide BBB to A*A*A*)',
    ieltsOverall: 7.0,
    ieltsComponent: 6.5,
    ieltsNote: 'Band-based: A is 7.5/7.0, B is 7.0/6.5, D is 6.5/6.0. Most courses checked are Band B.',
    satPolicy: 'accepted',
    satNote: "King's accepts APs, SAT, ACT, Honors and Dual Enrolment classes, alone or in combination. Whether SAT alone suffices is course-specific.",
    applicationSystem: 'UCAS',
    deadlineNote: 'LNAT for Law by 31 December in the admissions cycle. UCAT before applying for Medicine.',
    cycle: '2026 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.kcl.ac.uk/study/undergraduate/how-to-apply/entry-requirements',
      'https://www.kcl.ac.uk/study/undergraduate/how-to-apply/english-language-requirements',
    ],
    gaps: ['International tuition could not be read — the figures on every fee page are loaded by JavaScript. Check the course page directly.'],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine MBBS (A100)',
        ibPoints: 38, ibHl: 'aggregate 19 from three HL',
        hlRequired: ['Biology', 'Chemistry'],
        note: 'Grade 6 in both. No offers are made without an interview.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.kcl.ac.uk/study/undergraduate/courses/medicine-mbbs/requirements',
      },
      {
        area: 'Engineering', offered: true, course: 'General Engineering MEng',
        ibPoints: 36, ibPointsMin: 33, ibHl: 'aggregate 18 from three HL',
        hlRequired: ['Mathematics: Analysis and Approaches'],
        note: 'Grade 6. Physics is NOT required — unusual for engineering, and worth checking against your other choices.',
        source: 'https://www.kcl.ac.uk/study/undergraduate/courses/general-engineering-meng/entry-requirements',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 39, ibPointsMin: 36, ibHl: 'aggregate 20 from three HL',
        hlRequired: ['Mathematics: Analysis and Approaches'],
        hlRecommended: ['Computer Science'],
        source: 'https://www.kcl.ac.uk/study/undergraduate/courses/computer-science-bsc/requirements',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        ibPoints: 38, ibPointsMin: 35, ibHl: 'aggregate 19 from three HL',
        hlRequired: ['Mathematics'],
        note: 'Grade 6. Either Mathematics stream is accepted.',
        source: 'https://www.kcl.ac.uk/study/undergraduate/courses/economics-bsc/requirements',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 38, ibHl: 'aggregate 19 from three HL',
        note: 'No subject requirements. The 38 total includes TOK and the Extended Essay.',
        admissionsTest: 'LNAT',
        source: 'https://www.kcl.ac.uk/study/undergraduate/courses/law-llb/requirements',
      },
      { area: 'Architecture & Art', offered: false },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 38, ibPointsMin: 35, ibHl: 'aggregate 19 from three HL',
        hlRequired: ['one of Biology, Chemistry, Mathematics, Physics or Psychology'],
        source: 'https://www.kcl.ac.uk/study/undergraduate/courses/psychology-bsc/requirements',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'edinburgh',
    name: 'University of Edinburgh',
    city: 'Edinburgh',
    country: 'United Kingdom',
    tier: 'high',
    ibTypicalLow: 32,
    ibTypicalHigh: 43,
    ibNote: 'Edinburgh publishes each programme as a RANGE, e.g. "from 37 with 666 down to 32 with 655", plus a lower widening-access minimum. It also sets STANDARD LEVEL subject requirements, not only Higher Level. Where Mathematics is required it is Analysis and Approaches only.',
    aLevelTypical: 'A*A*A* – ABB depending on programme',
    ieltsOverall: 6.5,
    ieltsComponent: 5.5,
    ieltsNote: 'Medicine requires 7.5 with 7.5 in every component. Must be met in a single test.',
    satPolicy: 'unknown',
    applicationSystem: 'UCAS',
    cycle: '2027 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://study.ed.ac.uk/undergraduate/entry-requirements/international-qualifications/international-baccalaureate',
      'https://study.ed.ac.uk/undergraduate/entry-requirements/english-language',
    ],
    gaps: [
      'International tuition could not be read — every Edinburgh fee page returns policy prose without the fee tables.',
      'The Architecture page rendered with a 2026-entry breadcrumb while sibling programmes showed 2027; its figures may be one cycle behind.',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'MBChB Medicine (6 years)',
        ibPoints: 38, ibPointsMin: 34, ibHl: '6,6,6',
        hlRequired: ['Chemistry', 'one of Biology, Mathematics or Physics'],
        admissionsTest: 'UCAT', interview: true,
        source: 'https://study.ed.ac.uk/programmes/undergraduate/354-mbchb-medicine-6-year-programme/entry-requirements',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering MEng',
        ibPoints: 37, ibPointsMin: 32, ibHl: '6,6,6 down to 6,5,5',
        hlRequired: ['Mathematics: Analysis and Approaches', 'one of Physics, Biology, Chemistry, Computer Science or Design Technology'],
        note: 'Both at grade 5. Physics is preferred but not mandatory.',
        source: 'https://study.ed.ac.uk/programmes/undergraduate/83-mechanical-engineering/entry-requirements',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 43, ibPointsMin: 34, ibHl: '7,7,7 down to 6,6,5',
        hlRequired: ['Mathematics: Analysis and Approaches'],
        note: 'The published range is unusually wide — from 43 with 777 down to 34 with 665, with a widening-access minimum of 32. Mathematics at grade 6; other HLs can be any subject.',
        source: 'https://study.ed.ac.uk/programmes/undergraduate/57-computer-science/entry-requirements',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics MA',
        ibPoints: 40, ibPointsMin: 34, ibHl: '7,6,6 down to 6,6,6',
        hlRequired: ['Mathematics'],
        note: 'Grade 5.',
        source: 'https://study.ed.ac.uk/programmes/undergraduate/122-economics/entry-requirements',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 40, ibPointsMin: 34, ibHl: '7,6,6 down to 6,6,6',
        hlRequired: ['English'],
        note: 'Grade 5. No LNAT.',
        source: 'https://study.ed.ac.uk/programmes/undergraduate/168-law-ordinary-and-honours/entry-requirements',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Architecture BA/MA',
        ibPoints: 37, ibPointsMin: 34, ibHl: '6,6,6 down to 6,5,5',
        note: 'No HL subject required, but Standard Level English at 5 and Standard Level Mathematics at 6 are. Evidence of artistic ability is normally required — Visual Arts or Design Technology at HL or SL. No portfolio submission is stated.',
        source: 'https://study.ed.ac.uk/programmes/undergraduate/120-architecture/entry-requirements',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 37, ibPointsMin: 34, ibHl: '6,6,6 down to 6,5,5',
        hlRequired: ['one of Biology, Chemistry, Computer Science, Environmental Systems and Societies, Geography, Mathematics, Physics, Psychology, or Sports Exercise and Health Science'],
        note: 'At grade 5.',
        source: 'https://study.ed.ac.uk/programmes/undergraduate/370-psychology/entry-requirements',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'manchester',
    name: 'University of Manchester',
    city: 'Manchester',
    country: 'United Kingdom',
    tier: 'mid',
    ibTypicalLow: 36,
    ibTypicalHigh: 38,
    ibNote: 'Manchester publishes no university-wide figure and directs applicants to course pages. The range above is the courses actually checked.',
    aLevelTypical: 'AAA – A*A*A across the courses checked',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Course-specific, 6.5 to 7.0. TOEFL iBT Home Edition is not accepted.',
    satPolicy: 'accepted',
    satNote: 'One optional route to the GCSE-equivalent requirement: SAT 1290 or ACT 27. A high school diploma with GPA 3.0, APs or dual enrolment are alternatives.',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 28400,
    tuitionIntlMax: 60900,
    tuitionYear: '2026/27',
    applicationSystem: 'UCAS',
    cycle: '2027 entry (fees are 2026/27; 2027 fees not yet set)',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.manchester.ac.uk/study/international/admissions/language-requirements/',
      'https://www.manchester.ac.uk/study/international/country-specific-information/usa/entry-requirements/',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'MBChB Medicine',
        ibPoints: 36, ibHl: '6,6,6',
        hlRequired: ['Chemistry or Biology', 'another science'],
        note: 'Plus one further HL subject. UCAT Situational Judgement Band 3 or 4 is rejected outright.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/01428/mbchb-medicine/',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering MEng',
        ibPoints: 38, ibHl: '7,7,6 including Mathematics and Physics',
        hlRequired: ['Mathematics', 'Physics'],
        note: 'Either Mathematics stream. No interviews.',
        source: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03921/meng-mechanical-engineering/',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 37, ibHl: '7,6,6',
        hlRequired: ['Mathematics: Analysis and Approaches', 'one science (Computer Science, Physics, Chemistry or Biology)'],
        note: 'Mathematics at grade 7, Analysis and Approaches only — Applications and Interpretation is NOT accepted.',
        source: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00560/bsc-computer-science/',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        ibPoints: 36, ibHl: '6,6,6 including Mathematics',
        hlRequired: ['Mathematics'],
        source: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/10224/bsc-economics/',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 37, ibHl: '7,6,6',
        note: 'No HL subject required, but preference goes to applicants offering two subjects from a long published list of traditional academic subjects. No LNAT.',
        source: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/12446/llb-law/',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Architecture BA (Manchester School of Architecture)',
        ibPoints: 36, ibHl: '6,6,6',
        note: 'Run jointly with Manchester Metropolitan. Only applicants who meet the entry requirements are asked for a portfolio: a 450-word statement and 10–12 images of their own artwork.',
        portfolio: true,
        source: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00178/ba-architecture/',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 36, ibHl: '6,6,6',
        hlRequired: ['one of Chemistry, Biology, Physics, Psychology or Mathematics'],
        note: 'Candidates may be interviewed online or asked for an alternative admissions statement.',
        source: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00653/bsc-psychology/',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'warwick',
    name: 'University of Warwick',
    city: 'Coventry',
    country: 'United Kingdom',
    tier: 'high',
    ibTypicalLow: 34,
    ibTypicalHigh: 39,
    ibNote: 'Some courses state only a total with no HL pattern; others give both.',
    aLevelTypical: 'AAB – A*A*A',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Band A 6.0/5.5, Band B 6.5/6.0, Band C 7.0/6.5. Law and Economics are Band C.',
    satPolicy: 'unknown',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 27870,
    tuitionIntlMax: 35530,
    tuitionYear: '2026/27',
    applicationSystem: 'UCAS',
    deadlineNote: 'A pass at grade 4 in both GCSE English Language and Mathematics, or equivalent, is required for every course.',
    cycle: '2026 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://warwick.ac.uk/study/undergraduate/applying/entry-requirements/',
      'https://warwick.ac.uk/services/finance/studentfinance/fees/overseasfees/',
    ],
    gaps: ['A 2027-28 fee column appears on the overseas fees page but conflicts with the course pages, which say 2027-28 fees are not set. Re-check before quoting.'],
    areas: [
      {
        area: 'Medicine', offered: false,
        note: 'Warwick’s MB ChB is graduate-entry only — applicants must already hold an undergraduate degree. It is not open to school leavers.',
      },
      {
        area: 'Engineering', offered: true, course: 'Engineering MEng',
        ibPoints: 38, ibHl: '6,6,6',
        hlRequired: ['Mathematics or Physics'],
        note: 'Grade 6 in both Mathematics and Physics, but only ONE of the two must be at Higher Level — the other may be Standard Level. More flexible than most engineering courses here.',
        source: 'https://warwick.ac.uk/study/undergraduate/courses/meng-engineering/',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 39, ibPointsMin: 38, ibHl: '7,6,6',
        hlRequired: ['Mathematics: Analysis and Approaches'],
        note: 'Grade 7, Analysis and Approaches only. TMUA required unless eligible for a contextual offer.',
        admissionsTest: 'TMUA',
        source: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-computer-science/',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        ibPoints: 38, ibHl: 'including 6 in HL Mathematics',
        hlRequired: ['Mathematics'],
        note: 'Either Mathematics stream. TMUA is optional but encouraged and may factor into the offer decision.',
        admissionsTest: 'TMUA (optional)',
        source: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-economics/',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 38, ibPointsMin: 34,
        note: 'No HL subjects specified. Warwick does not require the LNAT. Contextual offer 34.',
        source: 'https://warwick.ac.uk/study/undergraduate/courses/llb-law/',
      },
      { area: 'Architecture & Art', offered: false },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 34,
        hlRecommended: ['Mathematics', 'Biology', 'Chemistry', 'Physics'],
        note: '34 overall if you have an HL science; 36 if you do not. The science is a discount, not a prerequisite.',
        source: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-psychology/',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'bristol',
    name: 'University of Bristol',
    city: 'Bristol',
    country: 'United Kingdom',
    tier: 'high',
    ibTypicalLow: 32,
    ibTypicalHigh: 40,
    ibNote: 'Offers read as "X points overall with 18 at Higher Level". Bristol accepts EITHER Mathematics stream wherever HL Mathematics is specified. Contextual offers are typically 4 points lower with 17 at HL.',
    aLevelTypical: 'AAA – A*AA',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Profile-based per course; Law and Psychology need 7.0 with 7.0 in writing, Medicine 7.5 with 7.0 throughout.',
    satPolicy: 'accepted',
    satNote: 'SAT evidence-based reading and writing 650, or ACT 28, as one accepted combination alongside APs, Honors and dual enrolment.',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 25500,
    tuitionIntlMax: 45800,
    tuitionYear: '2026 entry',
    applicationSystem: 'UCAS',
    deadlineNote: 'Medicine closes 15 October.',
    cycle: '2027 entry (fees are 2026 entry)',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.bristol.ac.uk/study/undergraduate/entry-requirements-qualifications/',
      'https://www.bristol.ac.uk/international/countries/baccalaureates.html',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'MB ChB Medicine',
        ibPoints: 36, ibHl: '18 HL points including 6,6',
        hlRequired: ['Chemistry', 'one of Biology, Physics or Mathematics'],
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.bristol.ac.uk/study/undergraduate/2027/medicine/mb-chb-medicine/',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering MEng',
        ibPoints: 38, ibPointsMin: 34, ibHl: '18 HL points including 7,6',
        hlRequired: ['Mathematics', 'one of Physics, Chemistry, Further Mathematics or Computer Science'],
        note: 'Either Mathematics stream.',
        source: 'https://www.bristol.ac.uk/study/undergraduate/2027/mechanical-engineering/meng-mechanical-engineering/',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 38, ibHl: '18 HL points including 7 in Mathematics',
        hlRequired: ['Mathematics'],
        note: 'Either Mathematics stream, at grade 7.',
        source: 'https://www.bristol.ac.uk/study/undergraduate/2027/computer-science/bsc-computer-science/',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        ibPoints: 38, ibHl: '18 HL points',
        hlRequired: ['Mathematics'],
        note: 'Satisfiable at Standard Level: HL Mathematics at 6 (either stream) OR SL Analysis and Approaches at 7.',
        source: 'https://www.bristol.ac.uk/study/undergraduate/2027/economics/bsc-economics/',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 38, ibPointsMin: 34, ibHl: '18 HL points',
        note: 'No subject requirements.',
        admissionsTest: 'LNAT',
        source: 'https://www.bristol.ac.uk/study/undergraduate/2027/law/llb-law/',
      },
      { area: 'Architecture & Art', offered: false },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 38, ibHl: '18 HL points including 6 in a science',
        hlRequired: ['a science-related subject'],
        note: 'Bristol does not publish which subjects count as science-related — check with the department before relying on this.',
        source: 'https://www.bristol.ac.uk/study/undergraduate/2027/psychology/bsc-psychology/',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'glasgow',
    name: 'University of Glasgow',
    city: 'Glasgow',
    country: 'United Kingdom',
    tier: 'mid',
    ibTypicalLow: 34,
    ibTypicalHigh: 38,
    ibNote: 'Glasgow publishes no university-wide figure by design. Offers are a total plus three HL grades, and many programmes add Standard Level subject minima on top.',
    aLevelTypical: 'BBB – AAA',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Medicine requires 7.0 with 7.0 in every sub-test. Tests must be within 2 years 5 months of the start date.',
    satPolicy: 'accepted',
    satNote: 'Three US routes: SAT 1280 or ACT 27 plus two APs at 4–5; or three APs at 4–5 with no standardised test; or test-optional with a 3.5 GPA and A grades in three higher-level classes.',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 27720,
    tuitionIntlMax: 62730,
    tuitionYear: '2026/27',
    applicationSystem: 'UCAS',
    deadlineNote: '15 October if the application includes Dentistry, Medicine, Veterinary Medicine, Oxford or Cambridge.',
    cycle: '2027 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.gla.ac.uk/undergraduate/entryrequirements/',
      'https://www.gla.ac.uk/undergraduate/fees/intlfees/',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine MBChB',
        ibPoints: 38, ibHl: '6,6,6',
        hlRequired: ['Chemistry', 'Biology'],
        note: 'Plus Standard Level Physics or Mathematics at 6, and Standard Level English at 6. Around 1,100 applicants are interviewed.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.gla.ac.uk/undergraduate/degrees/medicine/',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering BEng/MEng',
        ibPoints: 38, ibPointsMin: 34, ibHl: '6,6,6 (MEng); 6,5,5 (BEng)',
        hlRequired: ['Mathematics: Analysis and Approaches', 'Physics'],
        note: 'Standard Level 6 can be accepted for either Mathematics or Physics.',
        source: 'https://www.gla.ac.uk/undergraduate/degrees/mechanicalengineering/',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computing Science',
        ibPoints: 38, ibHl: '6,6,6',
        hlRequired: ['Mathematics: Analysis and Approaches'],
        note: 'Grade 6.',
        source: 'https://www.gla.ac.uk/undergraduate/degrees/computingscience/',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics',
        ibPoints: 36, ibHl: '6,6,5',
        hlRequired: ['Mathematics: Analysis and Approaches', 'English or a Humanities subject'],
        note: 'No prior study of economics is required.',
        source: 'https://www.gla.ac.uk/undergraduate/degrees/economics/',
      },
      {
        area: 'Law', offered: true, course: 'Common Law LLB',
        ibPoints: 38, ibHl: '6,6,6',
        hlRequired: ['a Humanities subject'],
        note: 'Plus Standard Level English at 6. Scots Law LLB is a separate programme with its own requirements.',
        admissionsTest: 'LNAT',
        source: 'https://www.gla.ac.uk/undergraduate/degrees/commonlaw/',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'History of Art MA',
        ibPoints: 34, ibHl: '6,5,5',
        hlRequired: ['English or a Humanities subject'],
        note: 'Glasgow has no RIBA-track undergraduate Architecture degree in the 2027 listing. History of Art is the nearest offering.',
        source: 'https://www.gla.ac.uk/undergraduate/degrees/historyofart/',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc / MA',
        ibPoints: 36, ibHl: '6,6,5',
        hlRequired: ['two sciences (BSc) or English/Humanities (MA)'],
        note: 'Plus Standard Level Mathematics at 4. The BSc and MA routes have different subject requirements.',
        source: 'https://www.gla.ac.uk/undergraduate/degrees/psychology/',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'durham',
    name: 'Durham University',
    city: 'Durham',
    country: 'United Kingdom',
    tier: 'high',
    ibTypicalLow: 35,
    ibTypicalHigh: 37,
    ibNote: 'Written as a total plus three HL grades in one string, e.g. "37 with 766". Several courses allow Standard Level Mathematics at a specified grade in place of HL.',
    aLevelTypical: 'AAB – A*AA; contextual offers commonly AAB',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Band-based; the band varies by course and was not verified per course.',
    satPolicy: 'unknown',
    satNote: 'US applicants at AP schools are expected to submit AP exams. No SAT or ACT position is published.',
    applicationSystem: 'UCAS',
    deadlineNote: 'The LNAT must be registered and sat in the same year as the application; results cannot be carried over.',
    cycle: 'September 2026 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.durham.ac.uk/study/undergraduate/how-to-apply/entry-requirements/',
      'https://www.durham.ac.uk/study/undergraduate/how-to-apply/entry-requirements/law-national-aptitude-test-lnat/',
    ],
    gaps: [
      'Tuition is published only inside a JavaScript course database. One figure was verified: £31,000 for Business and Management, September 2026.',
      'No undergraduate Medicine, Architecture or Fine Art surfaced in the course listing, but a full A–Z could not be loaded to confirm they are absent.',
    ],
    areas: [
      { area: 'Medicine', offered: false, note: 'No undergraduate Medicine course found in Durham’s listing. Treat as not found rather than confirmed absent.' },
      {
        area: 'Engineering', offered: true, course: 'General Engineering H100',
        ibPoints: 37, ibHl: '7,6,6',
        hlRequired: ['Mathematics', 'one of Biology, Chemistry or Physics'],
        source: 'https://www.durham.ac.uk/study/courses/general-engineering-h100/',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science G400',
        ibPoints: 37, ibHl: '7,6,6',
        hlRequired: ['Mathematics'],
        source: 'https://www.durham.ac.uk/study/courses/computer-science-g400/',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics L100',
        ibPoints: 37, ibHl: '7,6,6',
        hlRequired: ['Mathematics'],
        note: 'Standard Level Mathematics at 7 is accepted in place of HL. Business and Management N201 is a lower offer: 35 with 665, HL Mathematics or SL 5.',
        source: 'https://www.durham.ac.uk/business/courses/economics-l100/',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB M101',
        ibPoints: 37, ibHl: '7,6,6',
        note: 'No subject requirement. Durham’s own pages conflict on the LNAT: the dedicated LNAT page calls it essential, the general entry page calls it strongly encouraged. Sit it.',
        admissionsTest: 'LNAT',
        source: 'https://www.durham.ac.uk/study/courses/law-m101/',
      },
      { area: 'Architecture & Art', offered: false, note: 'No undergraduate Architecture or Fine Art degree found in Durham’s listing.' },
      {
        area: 'Psychology', offered: true, course: 'Psychology C800',
        ibPoints: 36, ibHl: '6,6,6',
        note: 'No HL subject required. GCSE-equivalent Mathematics at grade 5 is. BPS-accredited.',
        source: 'https://www.durham.ac.uk/study/courses/psychology-c800/',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'birmingham',
    name: 'University of Birmingham',
    city: 'Birmingham',
    country: 'United Kingdom',
    tier: 'mid',
    ibTypicalLow: 32,
    ibTypicalHigh: 32,
    ibNote: 'Birmingham holds the TOTAL at 32 across almost every course and loads the real requirement onto the Higher Level grades, which run from 6,5,5 to 7,6,6. Read the HL string, not the total — a 32 here is not comparable to a 32 elsewhere.',
    aLevelTypical: 'ABB – A*AA. General Studies is not accepted.',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Grouped: A (engineering, sciences, maths) 6.0/5.5; B (humanities, business, social sciences) 6.5/6.0; C (healthcare) 7.0/6.5; D (medicine, dentistry, nursing) 7.0/7.0.',
    satPolicy: 'unknown',
    applicationSystem: 'UCAS',
    cycle: '2027 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.birmingham.ac.uk/study/undergraduate/apply/entry-requirements/international-entry-requirements',
      'https://www.birmingham.ac.uk/study/undergraduate/fees-funding/tuition',
    ],
    gaps: [
      'International tuition is marked "To be confirmed" on every 2027-entry course page.',
      'The Economics BSc page returned HTTP 503 on repeated attempts, so Economics is unverified.',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine and Surgery MBChB (A100), 5 years',
        ibPoints: 32, ibHl: '6,6,6',
        hlRequired: ['Chemistry', 'a second science from Biology, Physics or Mathematics'],
        note: 'No minimum UCAT cut-off score is applied.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.birmingham.ac.uk/about/college-of-medicine-and-health/birmingham-medical-school/applying-to-medicine/entry-requirements-medicine-and-surgery-five-year',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering BEng',
        ibPoints: 32, ibHl: '6,6,5 including Mathematics',
        hlRequired: ['Mathematics'],
        hlRecommended: ['Physics', 'Further Mathematics'],
        note: 'Physics is explicitly advantageous but NOT required — unusual for mechanical engineering.',
        source: 'https://www.birmingham.ac.uk/study/undergraduate/subjects/mechanical-engineering-courses/mechanical-engineering-beng',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 32, ibHl: '7,6,6 including 6 in Mathematics',
        hlRequired: ['Mathematics'],
        note: 'Plus Standard Level English at 5.',
        source: 'https://www.birmingham.ac.uk/study/undergraduate/subjects/computer-science-courses/computer-science-bsc',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        note: 'Requirements could not be read — the course page returned a server error on every attempt. Check the university page directly.',
        source: 'https://www.birmingham.ac.uk/study/undergraduate/subjects/economics-courses/economics-bsc',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 32, ibHl: '6,6,6',
        note: 'No subject requirement. Birmingham explicitly does not require or consider the LNAT.',
        source: 'https://www.birmingham.ac.uk/study/undergraduate/subjects/law-courses/law-llb',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'History of Art BA',
        ibPoints: 32, ibHl: '6,5,5',
        note: 'No undergraduate Architecture degree was verified at Birmingham.',
        source: 'https://www.birmingham.ac.uk/study/undergraduate/subjects/history-of-art-courses/history-of-art-ba',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 32, ibHl: '6,6,6 – 6,6,5',
        note: 'The A-level route names a science subject, which implies an HL science expectation, but the page does not state one. Unconfirmed.',
        source: 'https://www.birmingham.ac.uk/study/undergraduate/subjects/psychology-and-neuroscience-courses/psychology-bsc',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'leeds',
    name: 'University of Leeds',
    city: 'Leeds',
    country: 'United Kingdom',
    tier: 'mid',
    ibTypicalLow: 34,
    ibTypicalHigh: 36,
    ibNote: 'Two different formats. Arts and social-science courses quote an overall total; Faculty of Engineering and Physical Sciences courses quote HIGHER LEVEL POINTS ONLY, with no overall total published at all. Leeds also asks a grade higher for Mathematics Applications and Interpretation than for Analysis and Approaches.',
    aLevelTypical: 'ABB – A*AA',
    ieltsOverall: 6.0,
    ieltsComponent: 5.5,
    ieltsNote: 'University minimum. Law, Economics and Psychology need 6.5/6.0; Medicine 7.5 with 7.5 in Spoken English.',
    satPolicy: 'unknown',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 29600,
    tuitionIntlMax: 50500,
    tuitionYear: '2027 entry',
    applicationSystem: 'UCAS',
    deadlineNote: 'Medicine 15 October in the year preceding entry.',
    cycle: '2027 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.leeds.ac.uk/international-applying/doc/entry-requirements',
      'https://www.leeds.ac.uk/undergraduate-fees/doc/fees-undergraduate-fees',
    ],
    gaps: ['Computer Science, Law, Economics and Psychology all show "To be confirmed" for international tuition while other Leeds courses have published 2027 figures.'],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine and Surgery MBChB',
        ibPoints: 36, ibHl: '6 in three HL subjects',
        hlRequired: ['Chemistry', 'Biology'],
        note: 'Both at grade 6. Multiple mini-interviews 4–6 January 2027, online for overseas applicants.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://courses.leeds.ac.uk/5580/medicine-and-surgery-mbchb',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering BEng',
        ibHl: '18 HL points',
        hlRequired: ['Mathematics', 'Physics or Chemistry'],
        note: 'Both at grade 6. Leeds publishes NO overall IB total for this course — only the Higher Level points.',
        source: 'https://courses.leeds.ac.uk/5200/mechanical-engineering-beng',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibHl: '18 HL points',
        hlRequired: ['Mathematics'],
        note: 'Analysis and Approaches at 5, or Applications and Interpretation at 6. No overall IB total is published for this course.',
        source: 'https://courses.leeds.ac.uk/3260/computer-science-bsc',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        ibPoints: 35, ibHl: '17 HL points',
        note: 'No HL subject is strictly required. Mathematics can be met at Standard Level 5 or Higher Level 4 — one of the most accommodating economics requirements in this file.',
        source: 'https://courses.leeds.ac.uk/f836/economics-bsc',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 35, ibHl: '6,6,5',
        note: 'No named subject, but two subjects must be traditional academic ones.',
        source: 'https://courses.leeds.ac.uk/3010/law-llb',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Art and Design BA (also Architecture MEng/BEng)',
        ibPoints: 34, ibHl: '16 HL points including 5 in Visual Arts and 4 in English',
        hlRequired: ['Visual Arts', 'English'],
        note: 'Leeds’ Architecture MEng/BEng is an ENGINEERING degree requiring HL Mathematics, not a portfolio-based design course. Art and Design BA is the creative route; applicants without an art qualification may substitute a portfolio.',
        source: 'https://courses.leeds.ac.uk/f254/art-and-design-ba',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 35, ibHl: 'a HL science at 6 or above',
        hlRequired: ['one science subject'],
        note: 'Interviews are not part of the standard admissions process.',
        source: 'https://courses.leeds.ac.uk/3670/psychology-bsc',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'southampton',
    name: 'University of Southampton',
    city: 'Southampton',
    country: 'United Kingdom',
    tier: 'mid',
    ibTypicalLow: 28,
    ibTypicalHigh: 38,
    ibNote: 'A total plus a required Higher Level subtotal, e.g. "36 points overall with 18 at Higher Level". Analysis and Approaches is accepted a grade lower than Applications and Interpretation on STEM courses.',
    aLevelTypical: 'BBC (Fine Art) – A*AA (Computer Science, Mechanical Engineering)',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Bands A–I set per course. Medicine requires 7.0 in every component.',
    satPolicy: 'unknown',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 26800,
    tuitionIntlMax: 64900,
    tuitionYear: 'not stated on the fee table',
    applicationSystem: 'UCAS',
    deadlineNote: 'Medicine: UCAT must be taken before the 15 October deadline.',
    cycle: '2026/27 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.southampton.ac.uk/courses/fees/undergraduate/tuition-fees.page',
      'https://www.southampton.ac.uk/international/english-language-requirements/test-band-scores',
    ],
    gaps: ['The Medicine page carries three different year labels at once and its fees disagree with the central fee table. Neither set is settled.'],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine BM5 (BMBS), 5 years',
        ibPoints: 36, ibHl: '18 HL points',
        hlRequired: ['Biology', 'one additional science'],
        note: 'Applicants meeting the requirements are ranked by UCAT score and the top cohort is interviewed.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.southampton.ac.uk/courses/medicine-bm5-degree-bmbs',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering MEng',
        ibPoints: 38, ibHl: '19 HL points',
        hlRequired: ['Mathematics', 'Physics'],
        note: 'Mathematics Analysis and Approaches at 6, or Applications and Interpretation at 7. Physics at 6.',
        source: 'https://www.southampton.ac.uk/courses/mechanical-engineering-degree-meng',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 38, ibHl: '19 HL points',
        hlRequired: ['Mathematics'],
        note: 'Grade 6, either stream.',
        source: 'https://www.southampton.ac.uk/courses/computer-science-degree-bsc',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        ibPoints: 34, ibHl: '17 HL points',
        hlRequired: ['Mathematics'],
        note: 'Grade 5, either stream.',
        source: 'https://www.southampton.ac.uk/courses/economics-degree-bsc',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 36, ibHl: '18 HL points',
        note: 'No named subject. Southampton explicitly does not require the LNAT. General Studies and Critical Thinking are excluded.',
        source: 'https://www.southampton.ac.uk/courses/law-degree-llb',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Fine Art BA, Winchester School of Art',
        ibPoints: 28, ibHl: '14 HL points',
        note: 'The lowest IB requirement in this file, but a portfolio of up to about 25 pieces — including sketchbooks and work from the past twelve months — is required from every applicant. No undergraduate Architecture degree was verified.',
        portfolio: true,
        source: 'https://www.southampton.ac.uk/courses/fine-art-degree-ba',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 34, ibHl: '6,6,5',
        hlRequired: ['one accepted science'],
        note: 'Accepted sciences: Biology, Chemistry, Physics, Mathematics, Psychology, Statistics, Environmental Science or Studies, Geography, Geology.',
        source: 'https://www.southampton.ac.uk/courses/psychology-degree-bsc',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'qmul',
    name: 'Queen Mary University of London',
    city: 'London',
    country: 'United Kingdom',
    tier: 'mid',
    ibTypicalLow: 30,
    ibTypicalHigh: 37,
    ibNote: 'Queen Mary publishes an A-level to IB mapping: AAA = 36 (6,6,6), AAB = 34 (6,6,5), ABB = 32 (6,5,5), BBB = 30 (5,5,5), with a handful of course exceptions.',
    aLevelTypical: 'BBB – A*AA; offers are normally expressed as three A-level grades',
    ieltsNote: 'Medicine requires 7.0 overall with 6.0 in all components. The university-wide English page could not be reached.',
    satPolicy: 'unknown',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 25000,
    tuitionIntlMax: 49950,
    tuitionYear: '2025/26',
    cycle: 'Mixed — 2027 for Medicine, undated elsewhere',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.qmul.ac.uk/undergraduate/apply/entry/',
      'https://www.qmul.ac.uk/fmd/study/undergraduate/courses/a100/entry-requirements/',
    ],
    gaps: [
      'The Queen Mary course finder returns HTTP 403 to automated readers, so Engineering, Computer Science, Law, Psychology and Architecture could not be verified at all — including whether they are offered.',
      'Tuition is 2025/26; Queen Mary raises international fees annually (3% in 2025/26), so 2027 will be higher.',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine MBBS (A100)',
        ibPoints: 37, ibHl: '6,6,6',
        hlRequired: ['Chemistry or Biology', 'a second science from Chemistry, Biology, Physics or Mathematics'],
        note: 'A UCAT total below the 4th decile is rejected at first shortlisting, as is Situational Judgement Band 4.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.qmul.ac.uk/fmd/study/undergraduate/courses/a100/entry-requirements/',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics and Finance',
        ibPoints: 36, ibHl: '6,6,6',
        hlRequired: ['Mathematics'],
        note: 'The page states Mathematics at Standard Level grade 6 minimum, which HL also satisfies. Mathematical Studies is not accepted. The page carries no year label.',
        source: 'https://www.qmul.ac.uk/sef/undergraduate/entry-requirements/',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'sheffield',
    name: 'University of Sheffield',
    city: 'Sheffield',
    country: 'United Kingdom',
    tier: 'mid',
    ibTypicalLow: 32,
    ibTypicalHigh: 38,
    ibNote: 'Official equivalence: 38 = A*AA, 36 = AAA, 34 = AAB, 33 = ABB, 32 = BBB. Several courses publish a lower "Access Sheffield" offer, and some accept a strong Extended Essay grade in place of a point.',
    aLevelTypical: 'BBB – A*AA',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Tiered: Standard 6.5/6.0, Good 7.0/6.5, Advanced 7.5/7.0, Proficiency 8.0/7.5.',
    satPolicy: 'unknown',
    satNote: 'Sheffield lists only Advanced Placement for US applicants: three APs at 5,5,5 plus a high school diploma with GPA 3.0 equals A*AA.',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 27650,
    tuitionIntlMax: 55000,
    tuitionYear: '2027/28',
    cycle: '2027 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.sheffield.ac.uk/new-students/tuition-fees/undergraduate-overseas',
      'https://sheffield.ac.uk/undergraduate/apply/international-qualifications',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine MBChB',
        ibPoints: 36, ibPointsMin: 34, ibHl: '6,6,6, with no Standard Level below 4',
        hlRequired: ['Chemistry or Biology', 'a second science'],
        note: 'UCAT minimum 1800 out of 2700 for 2027 entry — one of the few universities publishing a hard cut-off. International applicants are interviewed online.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://sheffield.ac.uk/undergraduate/courses/2027/medicine-mbchb',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering MEng',
        ibPoints: 38,
        hlRequired: ['Mathematics', 'one of Physics, Chemistry or Biology'],
        note: 'Mathematics at grade 6.',
        source: 'https://sheffield.ac.uk/undergraduate/courses/2027/mechanical-engineering-meng',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 38, ibPointsMin: 34,
        hlRequired: ['Mathematics'],
        note: 'Grade 6. Taking HL Computer Science as well lowers the total to 36. Access Sheffield offers run to 34.',
        source: 'https://sheffield.ac.uk/undergraduate/courses/2027/computer-science-bsc',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        ibPoints: 34, ibPointsMin: 33,
        hlRequired: ['Mathematics'],
        note: 'Grade 5. A grade B Extended Essay lowers the total to 33.',
        source: 'https://sheffield.ac.uk/undergraduate/courses/2027/economics-bsc',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 36, ibPointsMin: 34,
        note: 'No subject requirements and no LNAT. A grade A Extended Essay lowers the total to 34.',
        source: 'https://sheffield.ac.uk/undergraduate/courses/2027/law-llb',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Architecture BA',
        ibPoints: 36, ibPointsMin: 34,
        note: 'No HL subject required, but a maximum of two Art and Design or Design and Technology subjects are accepted. A portfolio of ten reproductions is assessed on observation, criticality, invention and representation. Interviews are not usual.',
        portfolio: true,
        source: 'https://sheffield.ac.uk/undergraduate/courses/2027/architecture-ba',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 34, ibPointsMin: 33,
        hlRequired: ['one science subject'],
        note: 'Grade 5. Accepted sciences: Biology, Chemistry, Environmental Science, Geography, Mathematics, Further Mathematics, Physics, Psychology, Statistics.',
        source: 'https://sheffield.ac.uk/undergraduate/courses/2027/psychology-bsc',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'nottingham',
    name: 'University of Nottingham',
    city: 'Nottingham',
    country: 'United Kingdom',
    tier: 'mid',
    ibTypicalLow: 34,
    ibTypicalHigh: 36,
    ibNote: 'Nottingham commonly offers an alternative Higher Level certificate route, e.g. "36 overall or 766 in 3 HL certificates". HL grade equivalence: A* = 7, A = 6, B = 5, C = 4.',
    aLevelTypical: 'BBC – A*AA',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Set per course, 6.0 to 7.5. Medicine 7.5 with 7.0 in every element; Law 6.5 with 6.5 in every element.',
    satPolicy: 'unknown',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 26200,
    tuitionIntlMax: 48900,
    tuitionYear: '2027/28',
    cycle: 'September 2027 entry',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.nottingham.ac.uk/studywithus/ugstudy/applying/entry-requirements.html',
      'https://www.nottingham.ac.uk/fees/tuitionfees/202728/undergraduate.aspx',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine BMBS',
        ibPoints: 34, ibHl: '6 in Biology and 6 in Chemistry',
        hlRequired: ['Biology', 'Chemistry'],
        note: 'A UCAT Situational Judgement Band 4 is not considered. Interviews 15 December 2026 and 29 January 2027, online for international applicants.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.nottingham.ac.uk/studywithus/ugstudy/courses/UG/Medicine-BMBS.html',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering MEng',
        ibPoints: 36, ibHl: '7,6,6',
        hlRequired: ['Mathematics', 'Physics'],
        note: 'Both at 6, but only ONE may sit at Standard Level: SL 7 in Analysis and Approaches, or SL 7 Physics. Applications and Interpretation is not accepted at Standard Level.',
        source: 'https://www.nottingham.ac.uk/studywithus/ugstudy/courses/UG/Mechanical-Engineering-MEng-Hons.html',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 36, ibPointsMin: 34, ibHl: '7,6,6',
        note: 'Nottingham requires NO Higher Level Mathematics for Computer Science — only GCSE-equivalent Mathematics at grade 5. This is a genuine outlier against Sheffield, Exeter and everyone else in this file, and it makes Nottingham the accessible route for a student without HL Maths. Taking HL Computer Science at 6 lowers the total to 34.',
        source: 'https://www.nottingham.ac.uk/studywithus/ugstudy/courses/UG/Computer-Science-BSc-Hons.html',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        ibPoints: 36, ibPointsMin: 34, ibHl: '7,6,6',
        note: 'Mathematics is required at some level — GCSE 7+, Standard Level 6, or Higher Level 4. Taking HL Mathematics lowers the total to 34.',
        source: 'https://www.nottingham.ac.uk/studywithus/ugstudy/courses/UG/Economics-BSc-Hons.html',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        ibPoints: 34, ibHl: '6,6,6',
        note: 'No named subject and no LNAT, but combinations with more than one non-traditional or practical Higher Level subject are not normally accepted.',
        source: 'https://www.nottingham.ac.uk/studywithus/ugstudy/courses/UG/Law-LLB-Hons.html',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Architecture BArch',
        ibPoints: 34, ibHl: '6,6,6',
        note: 'No HL subject required. Portfolio of 16 images across four categories: hand drawing, photography, 3D work, and creative media of choice. Virtual CAD designs are excluded.',
        portfolio: true,
        source: 'https://www.nottingham.ac.uk/studywithus/ugstudy/courses/UG/Architecture-BArch-Hons.html',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        ibPoints: 34, ibHl: '6,6,6',
        note: 'No HL subject required — unusually open for psychology. GCSE-equivalent English and Mathematics at grade 5.',
        source: 'https://www.nottingham.ac.uk/studywithus/ugstudy/courses/UG/Psychology-BSc-Hons.html',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'lancaster',
    name: 'Lancaster University',
    city: 'Lancaster',
    country: 'United Kingdom',
    tier: 'accessible',
    ibTypicalLow: 30,
    ibTypicalHigh: 36,
    ibNote: 'Official equivalence: AAA = 36 with 16 from three HL; AAB = 35 with 16 HL; ABB = 32 with 16 HL; BBB = 30 with 15 HL. Where a subject is required, Lancaster typically wants it at HL 6, and may sometimes consider SL 7 or HL 5.',
    aLevelTypical: 'ABB – AAA',
    ieltsOverall: 6.5,
    ieltsComponent: 5.5,
    ieltsNote: 'University-wide undergraduate minimum. Computer Science 6.0/5.5; Medicine 7.0 with 7.0 in each.',
    satPolicy: 'unknown',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 25490,
    tuitionIntlMax: 30770,
    tuitionYear: '2026/27',
    cycle: '2027 entry (pages incomplete; fees are 2026/27)',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.lancaster.ac.uk/study/entry-requirements/undergraduate-qualifications/',
      'https://www.lancaster.ac.uk/study/entry-requirements/undergraduate-english-requirements/',
    ],
    gaps: [
      'Lancaster hides course entry requirements in a JavaScript accordion. A-level grades come through, the IB line usually does not — only Computer Science yielded a figure.',
      'The two official Medicine pages contradict each other on grades and one is labelled 2025 entry. Treat Medicine here as low confidence.',
      'Engineering, Economics, Law, Fine Art and Psychology have A-level offers but no readable IB requirement.',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'Medicine and Surgery MBChB (A100)',
        hlRequired: ['two of Biology or Chemistry'],
        note: 'IB total not published on the 2027 page. The Medical School page (2025 wording) asks for three HL subjects at 6 including two of Biology and Chemistry, with SL subjects at 5. No applicant is offered a place without an in-person multiple mini-interview.',
        admissionsTest: 'UCAT', interview: true,
        source: 'https://www.lancaster.ac.uk/study/undergraduate/courses/medicine-and-surgery-mbchb-a100/2027/',
      },
      {
        area: 'Engineering', offered: true, course: 'Mechanical Engineering MEng',
        note: 'A-level offer AAA. The IB requirement did not render. Lancaster’s general guidance for engineering accepts SL Analysis and Approaches at 7 alongside HL Physics or Chemistry at 6.',
        source: 'https://www.lancaster.ac.uk/study/undergraduate/courses/mechanical-engineering-meng-hons-h303/2027/',
      },
      {
        area: 'Computer Science', offered: true, course: 'Computer Science BSc',
        ibPoints: 35, ibHl: '16 from the best three HL',
        note: 'No HL subject is required. HL Mathematics or Computer Science is considered for a LOWER offer — so, like Nottingham, a viable route for a student without HL Maths.',
        source: 'https://www.lancaster.ac.uk/study/undergraduate/courses/computer-science-bsc-hons-g400/2027/',
      },
      {
        area: 'Economics & Business', offered: true, course: 'Economics BSc',
        note: 'A-level offer AAB, no required subjects listed. IB requirement did not render; the university equivalence for AAB is 35 with 16 HL points.',
        source: 'https://www.lancaster.ac.uk/study/undergraduate/courses/economics-bsc-hons-l100/2026/',
      },
      {
        area: 'Law', offered: true, course: 'Law LLB',
        note: 'A-level offer AAB, no required subjects and no LNAT. IB requirement did not render; equivalence for AAB is 35 with 16 HL points.',
        source: 'https://www.lancaster.ac.uk/study/undergraduate/courses/law-llb-hons-m100/2026/',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'Fine Art BA',
        note: 'Lancaster has no Architecture degree. Fine Art A-level offer ABB; the IB requirement and any portfolio requirement did not render.',
        source: 'https://www.lancaster.ac.uk/study/undergraduate/courses/fine-art-ba-hons-w100/2027/',
      },
      {
        area: 'Psychology', offered: true, course: 'Psychology BSc',
        note: 'A-level offer AAB, no required subjects listed. IB requirement did not render.',
        source: 'https://www.lancaster.ac.uk/study/undergraduate/courses/psychology-bsc-hons-c800/2027/',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'exeter',
    name: 'University of Exeter',
    city: 'Exeter',
    country: 'United Kingdom',
    tier: 'mid',
    ibTypicalLow: 32,
    ibTypicalHigh: 38,
    ibNote: 'Offers are a total and a three-HL string together, e.g. 36/666. Equivalence: A*AA = 38 or 766; AAA = 36 or 666; BBB = 30 or 555. Contextual offers are typically two grades lower. Pure mathematics departments require Analysis and Approaches; other faculties accept either stream.',
    aLevelTypical: 'ABB – A*AA',
    ieltsOverall: 6.5,
    ieltsComponent: 6.0,
    ieltsNote: 'Profile-based. Psychology is Profile B2 (6.5/6.0); Medicine is Profile G (7.5/7.0). Profile B1, used by Law, Economics, Computer Science and Engineering, could not be read.',
    satPolicy: 'unknown',
    tuitionCurrency: 'GBP',
    tuitionIntlMin: 24900,
    tuitionIntlMax: 48900,
    tuitionYear: '2026 entry',
    applicationSystem: 'UCAS (institution code E84 EXETR)',
    deadlineNote: 'Medicine 1 September – 15 October. International applicants may be considered until 30 June if vacancies remain.',
    cycle: '2027 entry (fees are 2026 entry)',
    checkedOn: '2026-09-02',
    sources: [
      'https://www.exeter.ac.uk/undergraduate-degrees/entry-requirements/international-academic-qualifications/',
      'https://www.exeter.ac.uk/undergraduate-degrees/fees/',
    ],
    areas: [
      {
        area: 'Medicine', offered: true, course: 'BMBS Medicine',
        ibPoints: 38, ibPointsMin: 34, ibHl: '7,6,6',
        hlRequired: ['Chemistry', 'Biology'],
        note: 'Both at grade 6. Either UCAT or GAMSAT is accepted — unusual. Contextual offer 34/665.',
        admissionsTest: 'UCAT or GAMSAT', interview: true,
        source: 'https://www.exeter.ac.uk/undergraduate-degrees/bmbs-medicine/',
      },
      {
        area: 'Engineering', offered: true, course: 'BEng Engineering',
        ibPoints: 34, ibPointsMin: 32, ibHl: '6,6,5 down to 6,5,5',
        hlRequired: ['Mathematics', 'one other science'],
        note: 'Both at grade 5, either Mathematics stream. SL Mathematics at 7 plus HL Physics at 5 is also accepted.',
        source: 'https://www.exeter.ac.uk/undergraduate-degrees/beng-engineering/',
      },
      {
        area: 'Computer Science', offered: true, course: 'BSc Computer Science',
        ibPoints: 36, ibPointsMin: 30, ibHl: '6,6,6 down to 6,6,5',
        hlRequired: ['Mathematics'],
        note: 'Grade 5 only, either stream — among the lowest Mathematics bars of any computer science course here. No admissions test, no interview.',
        source: 'https://www.exeter.ac.uk/undergraduate-degrees/bsc-computer-science/',
      },
      {
        area: 'Economics & Business', offered: true, course: 'BSc Economics',
        ibPoints: 38, ibPointsMin: 32, ibHl: '7,6,6 down to 6,6,6',
        hlRequired: ['Mathematics'],
        note: 'HL 5 or SL 6, either stream. Mathematical Studies is not accepted.',
        source: 'https://www.exeter.ac.uk/undergraduate-degrees/bsc-economics/',
      },
      {
        area: 'Law', offered: true, course: 'LLB Law',
        ibPoints: 36, ibPointsMin: 32, ibHl: '6,6,6',
        note: 'No subject requirements, no LNAT, no interview. General Studies is not counted.',
        source: 'https://www.exeter.ac.uk/undergraduate-degrees/llb-law/',
      },
      {
        area: 'Architecture & Art', offered: true, course: 'BA Art History and Visual Culture',
        ibPoints: 32, ibPointsMin: 28, ibHl: '6,5,5',
        note: 'Exeter has no undergraduate Architecture degree. No subject requirements and no portfolio mentioned.',
        source: 'https://www.exeter.ac.uk/undergraduate-degrees/ba-art-history-and-visual-culture/',
      },
      {
        area: 'Psychology', offered: true, course: 'BSc Psychology',
        ibPoints: 36, ibPointsMin: 32, ibHl: '6,6,6',
        hlRequired: ['one science subject'],
        note: 'Grade 6. The accepted science list is broad: Biology, Chemistry, Computing, Design and Technology, Economics, Environmental Science, Geography, Geology, Mathematics, Physics, Psychology, Statistics.',
        source: 'https://www.exeter.ac.uk/undergraduate-degrees/bsc-psychology/',
      },
    ],
  },
]
